-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dr2_plus_dpt_int_cap is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    dr2 : IN STD_LOGIC_VECTOR (12 downto 0);
    pt1_V : IN STD_LOGIC_VECTOR (15 downto 0);
    pt2_V : IN STD_LOGIC_VECTOR (15 downto 0);
    ptscale_V : IN STD_LOGIC_VECTOR (16 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of dr2_plus_dpt_int_cap is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv15_16A0 : STD_LOGIC_VECTOR (14 downto 0) := "001011010100000";
    constant ap_const_lv25_1FFFFFF : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111111111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv13_179 : STD_LOGIC_VECTOR (12 downto 0) := "0000101111001";
    constant ap_const_lv32_75D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000011101011101";
    constant ap_const_lv12_75D : STD_LOGIC_VECTOR (11 downto 0) := "011101011101";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ptscale_V_read_reg_189 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal dr2_read_reg_194 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_2_fu_100_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_2_reg_200 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_1247_fu_107_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1247_reg_205 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal dpt_V_fu_64_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1246_fu_74_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_70_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_s_fu_82_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_90_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dpt2_V_cast_fu_174_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_V_fu_181_p2 : STD_LOGIC_VECTOR (41 downto 0);
    signal phitmp_fu_120_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal dr2_cast1_fu_111_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dq_fu_138_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_153_fu_129_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_cond_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_161_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal dpt2_V_cast_fu_174_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_152_fu_96_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal dpt2_V_cast_fu_174_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal r_V_fu_181_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_V_fu_181_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal r_V_fu_181_p00 : STD_LOGIC_VECTOR (41 downto 0);
    signal r_V_fu_181_p10 : STD_LOGIC_VECTOR (41 downto 0);

    component mp7wrapped_pfalgohbi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component mp7wrapped_pfalgoibs IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        dout : OUT STD_LOGIC_VECTOR (41 downto 0) );
    end component;



begin
    mp7wrapped_pfalgohbi_U1382 : component mp7wrapped_pfalgohbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 25)
    port map (
        din0 => dpt2_V_cast_fu_174_p0,
        din1 => dpt2_V_cast_fu_174_p1,
        dout => dpt2_V_cast_fu_174_p2);

    mp7wrapped_pfalgoibs_U1383 : component mp7wrapped_pfalgoibs
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 17,
        dout_WIDTH => 42)
    port map (
        din0 => r_V_fu_181_p0,
        din1 => r_V_fu_181_p1,
        dout => r_V_fu_181_p2);




    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                dr2_read_reg_194 <= dr2;
                p_2_reg_200 <= p_2_fu_100_p3;
                ptscale_V_read_reg_189 <= ptscale_V;
                tmp_1247_reg_205 <= tmp_1247_fu_107_p1;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        tmp_4_fu_161_p2 when (or_cond_fu_155_p2(0) = '1') else 
        ap_const_lv12_75D;
    dpt2_V_cast_fu_174_p0 <= tmp_152_fu_96_p1(15 - 1 downto 0);
    dpt2_V_cast_fu_174_p1 <= tmp_152_fu_96_p1(15 - 1 downto 0);
    dpt_V_fu_64_p2 <= std_logic_vector(unsigned(pt1_V) - unsigned(pt2_V));
    dq_fu_138_p2 <= std_logic_vector(unsigned(phitmp_fu_120_p4) + unsigned(dr2_cast1_fu_111_p1));
    dr2_cast1_fu_111_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dr2_read_reg_194),32));
    or_cond_fu_155_p2 <= (tmp_3_fu_149_p2 and tmp_2_fu_144_p2);
    p_2_fu_100_p3 <= 
        ap_const_lv25_1FFFFFF when (tmp_s_fu_90_p2(0) = '1') else 
        dpt2_V_cast_fu_174_p2;
    p_s_fu_82_p3 <= 
        ap_const_lv15_0 when (tmp_1246_fu_74_p3(0) = '1') else 
        tmp_fu_70_p1;
    phitmp_fu_120_p4 <= r_V_fu_181_p2(39 downto 8);
    r_V_fu_181_p0 <= r_V_fu_181_p00(25 - 1 downto 0);
    r_V_fu_181_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_2_reg_200),42));
    r_V_fu_181_p1 <= r_V_fu_181_p10(17 - 1 downto 0);
    r_V_fu_181_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ptscale_V_read_reg_189),42));
    tmp_1246_fu_74_p3 <= dpt_V_fu_64_p2(15 downto 15);
    tmp_1247_fu_107_p1 <= dr2(12 - 1 downto 0);
    tmp_152_fu_96_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_s_fu_82_p3),25));
    tmp_153_fu_129_p4 <= r_V_fu_181_p2(19 downto 8);
    tmp_2_fu_144_p2 <= "1" when (unsigned(dr2_read_reg_194) < unsigned(ap_const_lv13_179)) else "0";
    tmp_3_fu_149_p2 <= "1" when (signed(dq_fu_138_p2) < signed(ap_const_lv32_75D)) else "0";
    tmp_4_fu_161_p2 <= std_logic_vector(unsigned(tmp_153_fu_129_p4) + unsigned(tmp_1247_reg_205));
    tmp_fu_70_p1 <= dpt_V_fu_64_p2(15 - 1 downto 0);
    tmp_s_fu_90_p2 <= "1" when (unsigned(p_s_fu_82_p3) > unsigned(ap_const_lv15_16A0)) else "0";
end behav;
