-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity em2calo_sub is
port (
    ap_ready : OUT STD_LOGIC;
    calo_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_10_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_11_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_12_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_13_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_14_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_10_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_11_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_12_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_13_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_14_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_10_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_11_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_12_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_13_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_14_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_10_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_11_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_12_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_13_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_14_hwEmPt_V_re : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwIsEM_read : IN STD_LOGIC;
    calo_1_hwIsEM_read : IN STD_LOGIC;
    calo_2_hwIsEM_read : IN STD_LOGIC;
    calo_3_hwIsEM_read : IN STD_LOGIC;
    calo_4_hwIsEM_read : IN STD_LOGIC;
    calo_5_hwIsEM_read : IN STD_LOGIC;
    calo_6_hwIsEM_read : IN STD_LOGIC;
    calo_7_hwIsEM_read : IN STD_LOGIC;
    calo_8_hwIsEM_read : IN STD_LOGIC;
    calo_9_hwIsEM_read : IN STD_LOGIC;
    calo_10_hwIsEM_read : IN STD_LOGIC;
    calo_11_hwIsEM_read : IN STD_LOGIC;
    calo_12_hwIsEM_read : IN STD_LOGIC;
    calo_13_hwIsEM_read : IN STD_LOGIC;
    calo_14_hwIsEM_read : IN STD_LOGIC;
    sumem_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_12_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of em2calo_sub is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_s_fu_756_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_108_fu_770_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_fu_766_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_fu_744_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_fu_780_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_fu_750_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt36_fu_796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev36_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_808_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_109_fu_856_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_110_fu_870_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_1_fu_866_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_1_fu_844_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt37_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_1_fu_880_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_s_fu_850_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt38_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev38_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_908_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_908_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev37_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_111_fu_956_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_112_fu_970_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_2_fu_966_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_2_fu_944_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt39_fu_984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_2_fu_980_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_2_fu_950_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt40_fu_996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev40_fu_1002_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1008_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev39_fu_990_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_fu_1014_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_113_fu_1056_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_114_fu_1070_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_3_fu_1066_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_3_fu_1044_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt41_fu_1084_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_3_fu_1080_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_3_fu_1050_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt42_fu_1096_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev42_fu_1102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1108_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev41_fu_1090_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_115_fu_1156_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_116_fu_1170_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_4_fu_1166_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_4_fu_1144_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt43_fu_1184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_4_fu_1180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_4_fu_1150_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt44_fu_1196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev44_fu_1202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1208_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev43_fu_1190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp63_fu_1214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_117_fu_1256_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_118_fu_1270_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_5_fu_1266_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_5_fu_1244_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt45_fu_1284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_5_fu_1280_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_5_fu_1250_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt46_fu_1296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev46_fu_1302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp77_fu_1308_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp77_fu_1308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev45_fu_1290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp78_fu_1314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_119_fu_1356_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_120_fu_1370_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_6_fu_1366_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_6_fu_1344_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt47_fu_1384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_6_fu_1380_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_6_fu_1350_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt48_fu_1396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev48_fu_1402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp92_fu_1408_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp92_fu_1408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev47_fu_1390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp93_fu_1414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_121_fu_1456_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_122_fu_1470_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_7_fu_1466_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_7_fu_1444_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt49_fu_1484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_7_fu_1480_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_7_fu_1450_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt50_fu_1496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev50_fu_1502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp107_fu_1508_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp107_fu_1508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev49_fu_1490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp108_fu_1514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_123_fu_1556_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_124_fu_1570_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_8_fu_1566_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_8_fu_1544_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt51_fu_1584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_8_fu_1580_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_8_fu_1550_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt52_fu_1596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev52_fu_1602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp122_fu_1608_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp122_fu_1608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev51_fu_1590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp123_fu_1614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_125_fu_1656_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_126_fu_1670_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_s_fu_1666_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_9_fu_1644_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt53_fu_1684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_9_fu_1680_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_9_fu_1650_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt54_fu_1696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev54_fu_1702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp137_fu_1708_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp137_fu_1708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev53_fu_1690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp138_fu_1714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_127_fu_1756_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_128_fu_1770_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_10_fu_1766_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_s_fu_1744_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt55_fu_1784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_s_fu_1780_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_1_fu_1750_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt56_fu_1796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev56_fu_1802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp152_fu_1808_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp152_fu_1808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev55_fu_1790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp153_fu_1814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_129_fu_1856_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_130_fu_1870_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_11_fu_1866_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_10_fu_1844_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt57_fu_1884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_10_fu_1880_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_10_fu_1850_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt58_fu_1896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev58_fu_1902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp167_fu_1908_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp167_fu_1908_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev57_fu_1890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp168_fu_1914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_131_fu_1956_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_132_fu_1970_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_12_fu_1966_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_11_fu_1944_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt59_fu_1984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_11_fu_1980_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_11_fu_1950_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt60_fu_1996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev60_fu_2002_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp182_fu_2008_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp182_fu_2008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev59_fu_1990_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp183_fu_2014_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_133_fu_2056_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_134_fu_2070_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_13_fu_2066_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_12_fu_2044_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt61_fu_2084_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_12_fu_2080_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_12_fu_2050_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt62_fu_2096_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev62_fu_2102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp197_fu_2108_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp197_fu_2108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev61_fu_2090_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp198_fu_2114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_135_fu_2156_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_136_fu_2170_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_14_fu_2166_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_13_fu_2144_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt63_fu_2184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_13_fu_2180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_13_fu_2150_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal slt64_fu_2196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev64_fu_2202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp212_fu_2208_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp212_fu_2208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev63_fu_2190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp213_fu_2214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_out_0_hwPt_V_w_fu_820_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_1_hwPt_V_w_fu_920_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_2_hwPt_V_w_fu_1020_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_3_hwPt_V_w_fu_1120_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_4_hwPt_V_w_fu_1220_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_5_hwPt_V_w_fu_1320_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_6_hwPt_V_w_fu_1420_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_7_hwPt_V_w_fu_1528_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_8_hwPt_V_w_fu_1628_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_9_hwPt_V_w_fu_1728_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_10_hwPt_V_s_fu_1828_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_11_hwPt_V_s_fu_1928_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_12_hwPt_V_s_fu_2028_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_13_hwPt_V_s_fu_2128_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_14_hwPt_V_s_fu_2228_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_0_hwEta_V_s_fu_828_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_1_hwEta_V_s_fu_928_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_2_hwEta_V_s_fu_1028_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_3_hwEta_V_s_fu_1128_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_4_hwEta_V_s_fu_1228_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_5_hwEta_V_s_fu_1328_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_6_hwEta_V_s_fu_1428_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_7_hwEta_V_s_fu_1520_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_8_hwEta_V_s_fu_1620_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_9_hwEta_V_s_fu_1720_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_10_hwEta_V_fu_1820_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_11_hwEta_V_fu_1920_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_12_hwEta_V_fu_2020_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_13_hwEta_V_fu_2120_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_14_hwEta_V_fu_2220_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_0_hwPhi_V_s_fu_836_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_1_hwPhi_V_s_fu_936_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_2_hwPhi_V_s_fu_1036_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_3_hwPhi_V_s_fu_1136_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_4_hwPhi_V_s_fu_1236_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_5_hwPhi_V_s_fu_1336_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_6_hwPhi_V_s_fu_1436_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_7_hwPhi_V_s_fu_1536_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_8_hwPhi_V_s_fu_1636_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_9_hwPhi_V_s_fu_1736_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_10_hwPhi_V_fu_1836_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_11_hwPhi_V_fu_1936_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_12_hwPhi_V_fu_2036_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_13_hwPhi_V_fu_2136_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_14_hwPhi_V_fu_2236_p3 : STD_LOGIC_VECTOR (9 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= calo_out_0_hwPt_V_w_fu_820_p3;
    ap_return_1 <= calo_out_1_hwPt_V_w_fu_920_p3;
    ap_return_10 <= calo_out_10_hwPt_V_s_fu_1828_p3;
    ap_return_11 <= calo_out_11_hwPt_V_s_fu_1928_p3;
    ap_return_12 <= calo_out_12_hwPt_V_s_fu_2028_p3;
    ap_return_13 <= calo_out_13_hwPt_V_s_fu_2128_p3;
    ap_return_14 <= calo_out_14_hwPt_V_s_fu_2228_p3;
    ap_return_15 <= calo_out_0_hwEta_V_s_fu_828_p3;
    ap_return_16 <= calo_out_1_hwEta_V_s_fu_928_p3;
    ap_return_17 <= calo_out_2_hwEta_V_s_fu_1028_p3;
    ap_return_18 <= calo_out_3_hwEta_V_s_fu_1128_p3;
    ap_return_19 <= calo_out_4_hwEta_V_s_fu_1228_p3;
    ap_return_2 <= calo_out_2_hwPt_V_w_fu_1020_p3;
    ap_return_20 <= calo_out_5_hwEta_V_s_fu_1328_p3;
    ap_return_21 <= calo_out_6_hwEta_V_s_fu_1428_p3;
    ap_return_22 <= calo_out_7_hwEta_V_s_fu_1520_p3;
    ap_return_23 <= calo_out_8_hwEta_V_s_fu_1620_p3;
    ap_return_24 <= calo_out_9_hwEta_V_s_fu_1720_p3;
    ap_return_25 <= calo_out_10_hwEta_V_fu_1820_p3;
    ap_return_26 <= calo_out_11_hwEta_V_fu_1920_p3;
    ap_return_27 <= calo_out_12_hwEta_V_fu_2020_p3;
    ap_return_28 <= calo_out_13_hwEta_V_fu_2120_p3;
    ap_return_29 <= calo_out_14_hwEta_V_fu_2220_p3;
    ap_return_3 <= calo_out_3_hwPt_V_w_fu_1120_p3;
    ap_return_30 <= calo_out_0_hwPhi_V_s_fu_836_p3;
    ap_return_31 <= calo_out_1_hwPhi_V_s_fu_936_p3;
    ap_return_32 <= calo_out_2_hwPhi_V_s_fu_1036_p3;
    ap_return_33 <= calo_out_3_hwPhi_V_s_fu_1136_p3;
    ap_return_34 <= calo_out_4_hwPhi_V_s_fu_1236_p3;
    ap_return_35 <= calo_out_5_hwPhi_V_s_fu_1336_p3;
    ap_return_36 <= calo_out_6_hwPhi_V_s_fu_1436_p3;
    ap_return_37 <= calo_out_7_hwPhi_V_s_fu_1536_p3;
    ap_return_38 <= calo_out_8_hwPhi_V_s_fu_1636_p3;
    ap_return_39 <= calo_out_9_hwPhi_V_s_fu_1736_p3;
    ap_return_4 <= calo_out_4_hwPt_V_w_fu_1220_p3;
    ap_return_40 <= calo_out_10_hwPhi_V_fu_1836_p3;
    ap_return_41 <= calo_out_11_hwPhi_V_fu_1936_p3;
    ap_return_42 <= calo_out_12_hwPhi_V_fu_2036_p3;
    ap_return_43 <= calo_out_13_hwPhi_V_fu_2136_p3;
    ap_return_44 <= calo_out_14_hwPhi_V_fu_2236_p3;
    ap_return_5 <= calo_out_5_hwPt_V_w_fu_1320_p3;
    ap_return_6 <= calo_out_6_hwPt_V_w_fu_1420_p3;
    ap_return_7 <= calo_out_7_hwPt_V_w_fu_1528_p3;
    ap_return_8 <= calo_out_8_hwPt_V_w_fu_1628_p3;
    ap_return_9 <= calo_out_9_hwPt_V_w_fu_1728_p3;
    calo_out_0_hwEta_V_s_fu_828_p3 <= 
        ap_const_lv10_0 when (sel_tmp3_fu_814_p2(0) = '1') else 
        calo_0_hwEta_V_read;
    calo_out_0_hwPhi_V_s_fu_836_p3 <= 
        ap_const_lv10_0 when (sel_tmp3_fu_814_p2(0) = '1') else 
        calo_0_hwPhi_V_read;
    calo_out_0_hwPt_V_w_fu_820_p3 <= 
        ap_const_lv16_0 when (sel_tmp3_fu_814_p2(0) = '1') else 
        ptsub_V_fu_744_p2;
    calo_out_10_hwEta_V_fu_1820_p3 <= 
        ap_const_lv10_0 when (sel_tmp153_fu_1814_p2(0) = '1') else 
        calo_10_hwEta_V_rea;
    calo_out_10_hwPhi_V_fu_1836_p3 <= 
        ap_const_lv10_0 when (sel_tmp153_fu_1814_p2(0) = '1') else 
        calo_10_hwPhi_V_rea;
    calo_out_10_hwPt_V_s_fu_1828_p3 <= 
        ap_const_lv16_0 when (sel_tmp153_fu_1814_p2(0) = '1') else 
        ptsub_V_s_fu_1744_p2;
    calo_out_11_hwEta_V_fu_1920_p3 <= 
        ap_const_lv10_0 when (sel_tmp168_fu_1914_p2(0) = '1') else 
        calo_11_hwEta_V_rea;
    calo_out_11_hwPhi_V_fu_1936_p3 <= 
        ap_const_lv10_0 when (sel_tmp168_fu_1914_p2(0) = '1') else 
        calo_11_hwPhi_V_rea;
    calo_out_11_hwPt_V_s_fu_1928_p3 <= 
        ap_const_lv16_0 when (sel_tmp168_fu_1914_p2(0) = '1') else 
        ptsub_V_10_fu_1844_p2;
    calo_out_12_hwEta_V_fu_2020_p3 <= 
        ap_const_lv10_0 when (sel_tmp183_fu_2014_p2(0) = '1') else 
        calo_12_hwEta_V_rea;
    calo_out_12_hwPhi_V_fu_2036_p3 <= 
        ap_const_lv10_0 when (sel_tmp183_fu_2014_p2(0) = '1') else 
        calo_12_hwPhi_V_rea;
    calo_out_12_hwPt_V_s_fu_2028_p3 <= 
        ap_const_lv16_0 when (sel_tmp183_fu_2014_p2(0) = '1') else 
        ptsub_V_11_fu_1944_p2;
    calo_out_13_hwEta_V_fu_2120_p3 <= 
        ap_const_lv10_0 when (sel_tmp198_fu_2114_p2(0) = '1') else 
        calo_13_hwEta_V_rea;
    calo_out_13_hwPhi_V_fu_2136_p3 <= 
        ap_const_lv10_0 when (sel_tmp198_fu_2114_p2(0) = '1') else 
        calo_13_hwPhi_V_rea;
    calo_out_13_hwPt_V_s_fu_2128_p3 <= 
        ap_const_lv16_0 when (sel_tmp198_fu_2114_p2(0) = '1') else 
        ptsub_V_12_fu_2044_p2;
    calo_out_14_hwEta_V_fu_2220_p3 <= 
        ap_const_lv10_0 when (sel_tmp213_fu_2214_p2(0) = '1') else 
        calo_14_hwEta_V_rea;
    calo_out_14_hwPhi_V_fu_2236_p3 <= 
        ap_const_lv10_0 when (sel_tmp213_fu_2214_p2(0) = '1') else 
        calo_14_hwPhi_V_rea;
    calo_out_14_hwPt_V_s_fu_2228_p3 <= 
        ap_const_lv16_0 when (sel_tmp213_fu_2214_p2(0) = '1') else 
        ptsub_V_13_fu_2144_p2;
    calo_out_1_hwEta_V_s_fu_928_p3 <= 
        ap_const_lv10_0 when (sel_tmp18_fu_914_p2(0) = '1') else 
        calo_1_hwEta_V_read;
    calo_out_1_hwPhi_V_s_fu_936_p3 <= 
        ap_const_lv10_0 when (sel_tmp18_fu_914_p2(0) = '1') else 
        calo_1_hwPhi_V_read;
    calo_out_1_hwPt_V_w_fu_920_p3 <= 
        ap_const_lv16_0 when (sel_tmp18_fu_914_p2(0) = '1') else 
        ptsub_V_1_fu_844_p2;
    calo_out_2_hwEta_V_s_fu_1028_p3 <= 
        ap_const_lv10_0 when (sel_tmp33_fu_1014_p2(0) = '1') else 
        calo_2_hwEta_V_read;
    calo_out_2_hwPhi_V_s_fu_1036_p3 <= 
        ap_const_lv10_0 when (sel_tmp33_fu_1014_p2(0) = '1') else 
        calo_2_hwPhi_V_read;
    calo_out_2_hwPt_V_w_fu_1020_p3 <= 
        ap_const_lv16_0 when (sel_tmp33_fu_1014_p2(0) = '1') else 
        ptsub_V_2_fu_944_p2;
    calo_out_3_hwEta_V_s_fu_1128_p3 <= 
        ap_const_lv10_0 when (sel_tmp48_fu_1114_p2(0) = '1') else 
        calo_3_hwEta_V_read;
    calo_out_3_hwPhi_V_s_fu_1136_p3 <= 
        ap_const_lv10_0 when (sel_tmp48_fu_1114_p2(0) = '1') else 
        calo_3_hwPhi_V_read;
    calo_out_3_hwPt_V_w_fu_1120_p3 <= 
        ap_const_lv16_0 when (sel_tmp48_fu_1114_p2(0) = '1') else 
        ptsub_V_3_fu_1044_p2;
    calo_out_4_hwEta_V_s_fu_1228_p3 <= 
        ap_const_lv10_0 when (sel_tmp63_fu_1214_p2(0) = '1') else 
        calo_4_hwEta_V_read;
    calo_out_4_hwPhi_V_s_fu_1236_p3 <= 
        ap_const_lv10_0 when (sel_tmp63_fu_1214_p2(0) = '1') else 
        calo_4_hwPhi_V_read;
    calo_out_4_hwPt_V_w_fu_1220_p3 <= 
        ap_const_lv16_0 when (sel_tmp63_fu_1214_p2(0) = '1') else 
        ptsub_V_4_fu_1144_p2;
    calo_out_5_hwEta_V_s_fu_1328_p3 <= 
        ap_const_lv10_0 when (sel_tmp78_fu_1314_p2(0) = '1') else 
        calo_5_hwEta_V_read;
    calo_out_5_hwPhi_V_s_fu_1336_p3 <= 
        ap_const_lv10_0 when (sel_tmp78_fu_1314_p2(0) = '1') else 
        calo_5_hwPhi_V_read;
    calo_out_5_hwPt_V_w_fu_1320_p3 <= 
        ap_const_lv16_0 when (sel_tmp78_fu_1314_p2(0) = '1') else 
        ptsub_V_5_fu_1244_p2;
    calo_out_6_hwEta_V_s_fu_1428_p3 <= 
        ap_const_lv10_0 when (sel_tmp93_fu_1414_p2(0) = '1') else 
        calo_6_hwEta_V_read;
    calo_out_6_hwPhi_V_s_fu_1436_p3 <= 
        ap_const_lv10_0 when (sel_tmp93_fu_1414_p2(0) = '1') else 
        calo_6_hwPhi_V_read;
    calo_out_6_hwPt_V_w_fu_1420_p3 <= 
        ap_const_lv16_0 when (sel_tmp93_fu_1414_p2(0) = '1') else 
        ptsub_V_6_fu_1344_p2;
    calo_out_7_hwEta_V_s_fu_1520_p3 <= 
        ap_const_lv10_0 when (sel_tmp108_fu_1514_p2(0) = '1') else 
        calo_7_hwEta_V_read;
    calo_out_7_hwPhi_V_s_fu_1536_p3 <= 
        ap_const_lv10_0 when (sel_tmp108_fu_1514_p2(0) = '1') else 
        calo_7_hwPhi_V_read;
    calo_out_7_hwPt_V_w_fu_1528_p3 <= 
        ap_const_lv16_0 when (sel_tmp108_fu_1514_p2(0) = '1') else 
        ptsub_V_7_fu_1444_p2;
    calo_out_8_hwEta_V_s_fu_1620_p3 <= 
        ap_const_lv10_0 when (sel_tmp123_fu_1614_p2(0) = '1') else 
        calo_8_hwEta_V_read;
    calo_out_8_hwPhi_V_s_fu_1636_p3 <= 
        ap_const_lv10_0 when (sel_tmp123_fu_1614_p2(0) = '1') else 
        calo_8_hwPhi_V_read;
    calo_out_8_hwPt_V_w_fu_1628_p3 <= 
        ap_const_lv16_0 when (sel_tmp123_fu_1614_p2(0) = '1') else 
        ptsub_V_8_fu_1544_p2;
    calo_out_9_hwEta_V_s_fu_1720_p3 <= 
        ap_const_lv10_0 when (sel_tmp138_fu_1714_p2(0) = '1') else 
        calo_9_hwEta_V_read;
    calo_out_9_hwPhi_V_s_fu_1736_p3 <= 
        ap_const_lv10_0 when (sel_tmp138_fu_1714_p2(0) = '1') else 
        calo_9_hwPhi_V_read;
    calo_out_9_hwPt_V_w_fu_1728_p3 <= 
        ap_const_lv16_0 when (sel_tmp138_fu_1714_p2(0) = '1') else 
        ptsub_V_9_fu_1644_p2;
    emsub_V_10_fu_1850_p2 <= std_logic_vector(unsigned(calo_11_hwEmPt_V_re) - unsigned(sumem_11_V_read));
    emsub_V_11_fu_1950_p2 <= std_logic_vector(unsigned(calo_12_hwEmPt_V_re) - unsigned(sumem_12_V_read));
    emsub_V_12_fu_2050_p2 <= std_logic_vector(unsigned(calo_13_hwEmPt_V_re) - unsigned(sumem_13_V_read));
    emsub_V_13_fu_2150_p2 <= std_logic_vector(unsigned(calo_14_hwEmPt_V_re) - unsigned(sumem_14_V_read));
    emsub_V_1_fu_1750_p2 <= std_logic_vector(unsigned(calo_10_hwEmPt_V_re) - unsigned(sumem_10_V_read));
    emsub_V_2_fu_950_p2 <= std_logic_vector(unsigned(calo_2_hwEmPt_V_rea) - unsigned(sumem_2_V_read));
    emsub_V_3_fu_1050_p2 <= std_logic_vector(unsigned(calo_3_hwEmPt_V_rea) - unsigned(sumem_3_V_read));
    emsub_V_4_fu_1150_p2 <= std_logic_vector(unsigned(calo_4_hwEmPt_V_rea) - unsigned(sumem_4_V_read));
    emsub_V_5_fu_1250_p2 <= std_logic_vector(unsigned(calo_5_hwEmPt_V_rea) - unsigned(sumem_5_V_read));
    emsub_V_6_fu_1350_p2 <= std_logic_vector(unsigned(calo_6_hwEmPt_V_rea) - unsigned(sumem_6_V_read));
    emsub_V_7_fu_1450_p2 <= std_logic_vector(unsigned(calo_7_hwEmPt_V_rea) - unsigned(sumem_7_V_read));
    emsub_V_8_fu_1550_p2 <= std_logic_vector(unsigned(calo_8_hwEmPt_V_rea) - unsigned(sumem_8_V_read));
    emsub_V_9_fu_1650_p2 <= std_logic_vector(unsigned(calo_9_hwEmPt_V_rea) - unsigned(sumem_9_V_read));
    emsub_V_fu_750_p2 <= std_logic_vector(unsigned(calo_0_hwEmPt_V_rea) - unsigned(sumem_0_V_read));
    emsub_V_s_fu_850_p2 <= std_logic_vector(unsigned(calo_1_hwEmPt_V_rea) - unsigned(sumem_1_V_read));
    ptsub_V_10_fu_1844_p2 <= std_logic_vector(unsigned(calo_11_hwPt_V_read) - unsigned(sumem_11_V_read));
    ptsub_V_11_fu_1944_p2 <= std_logic_vector(unsigned(calo_12_hwPt_V_read) - unsigned(sumem_12_V_read));
    ptsub_V_12_fu_2044_p2 <= std_logic_vector(unsigned(calo_13_hwPt_V_read) - unsigned(sumem_13_V_read));
    ptsub_V_13_fu_2144_p2 <= std_logic_vector(unsigned(calo_14_hwPt_V_read) - unsigned(sumem_14_V_read));
    ptsub_V_1_fu_844_p2 <= std_logic_vector(unsigned(calo_1_hwPt_V_read) - unsigned(sumem_1_V_read));
    ptsub_V_2_fu_944_p2 <= std_logic_vector(unsigned(calo_2_hwPt_V_read) - unsigned(sumem_2_V_read));
    ptsub_V_3_fu_1044_p2 <= std_logic_vector(unsigned(calo_3_hwPt_V_read) - unsigned(sumem_3_V_read));
    ptsub_V_4_fu_1144_p2 <= std_logic_vector(unsigned(calo_4_hwPt_V_read) - unsigned(sumem_4_V_read));
    ptsub_V_5_fu_1244_p2 <= std_logic_vector(unsigned(calo_5_hwPt_V_read) - unsigned(sumem_5_V_read));
    ptsub_V_6_fu_1344_p2 <= std_logic_vector(unsigned(calo_6_hwPt_V_read) - unsigned(sumem_6_V_read));
    ptsub_V_7_fu_1444_p2 <= std_logic_vector(unsigned(calo_7_hwPt_V_read) - unsigned(sumem_7_V_read));
    ptsub_V_8_fu_1544_p2 <= std_logic_vector(unsigned(calo_8_hwPt_V_read) - unsigned(sumem_8_V_read));
    ptsub_V_9_fu_1644_p2 <= std_logic_vector(unsigned(calo_9_hwPt_V_read) - unsigned(sumem_9_V_read));
    ptsub_V_fu_744_p2 <= std_logic_vector(unsigned(calo_0_hwPt_V_read) - unsigned(sumem_0_V_read));
    ptsub_V_s_fu_1744_p2 <= std_logic_vector(unsigned(calo_10_hwPt_V_read) - unsigned(sumem_10_V_read));
        r_V_10_fu_1766_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_127_fu_1756_p4),16));

        r_V_11_fu_1866_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_129_fu_1856_p4),16));

        r_V_12_fu_1966_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_131_fu_1956_p4),16));

        r_V_13_fu_2066_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_133_fu_2056_p4),16));

        r_V_14_fu_2166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_135_fu_2156_p4),16));

        r_V_1_fu_866_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_109_fu_856_p4),16));

        r_V_2_fu_966_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_111_fu_956_p4),16));

        r_V_3_fu_1066_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_113_fu_1056_p4),16));

        r_V_4_fu_1166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_115_fu_1156_p4),16));

        r_V_5_fu_1266_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_117_fu_1256_p4),16));

        r_V_6_fu_1366_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_119_fu_1356_p4),16));

        r_V_7_fu_1466_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_121_fu_1456_p4),16));

        r_V_8_fu_1566_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_123_fu_1556_p4),16));

        r_V_9_10_fu_1880_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_130_fu_1870_p4),16));

        r_V_9_11_fu_1980_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_132_fu_1970_p4),16));

        r_V_9_12_fu_2080_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_134_fu_2070_p4),16));

        r_V_9_13_fu_2180_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_136_fu_2170_p4),16));

        r_V_9_1_fu_880_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_110_fu_870_p4),16));

        r_V_9_2_fu_980_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_112_fu_970_p4),16));

        r_V_9_3_fu_1080_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_114_fu_1070_p4),16));

        r_V_9_4_fu_1180_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_116_fu_1170_p4),16));

        r_V_9_5_fu_1280_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_118_fu_1270_p4),16));

        r_V_9_6_fu_1380_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_120_fu_1370_p4),16));

        r_V_9_7_fu_1480_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_122_fu_1470_p4),16));

        r_V_9_8_fu_1580_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_124_fu_1570_p4),16));

        r_V_9_9_fu_1680_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_126_fu_1670_p4),16));

        r_V_9_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_108_fu_770_p4),16));

        r_V_9_s_fu_1780_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_128_fu_1770_p4),16));

        r_V_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_756_p4),16));

        r_V_s_fu_1666_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_125_fu_1656_p4),16));

    rev36_fu_802_p2 <= (slt36_fu_796_p2 xor ap_const_lv1_1);
    rev37_fu_890_p2 <= (slt37_fu_884_p2 xor ap_const_lv1_1);
    rev38_fu_902_p2 <= (slt38_fu_896_p2 xor ap_const_lv1_1);
    rev39_fu_990_p2 <= (slt39_fu_984_p2 xor ap_const_lv1_1);
    rev40_fu_1002_p2 <= (slt40_fu_996_p2 xor ap_const_lv1_1);
    rev41_fu_1090_p2 <= (slt41_fu_1084_p2 xor ap_const_lv1_1);
    rev42_fu_1102_p2 <= (slt42_fu_1096_p2 xor ap_const_lv1_1);
    rev43_fu_1190_p2 <= (slt43_fu_1184_p2 xor ap_const_lv1_1);
    rev44_fu_1202_p2 <= (slt44_fu_1196_p2 xor ap_const_lv1_1);
    rev45_fu_1290_p2 <= (slt45_fu_1284_p2 xor ap_const_lv1_1);
    rev46_fu_1302_p2 <= (slt46_fu_1296_p2 xor ap_const_lv1_1);
    rev47_fu_1390_p2 <= (slt47_fu_1384_p2 xor ap_const_lv1_1);
    rev48_fu_1402_p2 <= (slt48_fu_1396_p2 xor ap_const_lv1_1);
    rev49_fu_1490_p2 <= (slt49_fu_1484_p2 xor ap_const_lv1_1);
    rev50_fu_1502_p2 <= (slt50_fu_1496_p2 xor ap_const_lv1_1);
    rev51_fu_1590_p2 <= (slt51_fu_1584_p2 xor ap_const_lv1_1);
    rev52_fu_1602_p2 <= (slt52_fu_1596_p2 xor ap_const_lv1_1);
    rev53_fu_1690_p2 <= (slt53_fu_1684_p2 xor ap_const_lv1_1);
    rev54_fu_1702_p2 <= (slt54_fu_1696_p2 xor ap_const_lv1_1);
    rev55_fu_1790_p2 <= (slt55_fu_1784_p2 xor ap_const_lv1_1);
    rev56_fu_1802_p2 <= (slt56_fu_1796_p2 xor ap_const_lv1_1);
    rev57_fu_1890_p2 <= (slt57_fu_1884_p2 xor ap_const_lv1_1);
    rev58_fu_1902_p2 <= (slt58_fu_1896_p2 xor ap_const_lv1_1);
    rev59_fu_1990_p2 <= (slt59_fu_1984_p2 xor ap_const_lv1_1);
    rev60_fu_2002_p2 <= (slt60_fu_1996_p2 xor ap_const_lv1_1);
    rev61_fu_2090_p2 <= (slt61_fu_2084_p2 xor ap_const_lv1_1);
    rev62_fu_2102_p2 <= (slt62_fu_2096_p2 xor ap_const_lv1_1);
    rev63_fu_2190_p2 <= (slt63_fu_2184_p2 xor ap_const_lv1_1);
    rev64_fu_2202_p2 <= (slt64_fu_2196_p2 xor ap_const_lv1_1);
    rev_fu_790_p2 <= (slt_fu_784_p2 xor ap_const_lv1_1);
    sel_tmp107_fu_1508_p1 <= (0=>calo_7_hwIsEM_read, others=>'-');
    sel_tmp107_fu_1508_p2 <= (sel_tmp107_fu_1508_p1 and rev50_fu_1502_p2);
    sel_tmp108_fu_1514_p2 <= (sel_tmp107_fu_1508_p2 or rev49_fu_1490_p2);
    sel_tmp122_fu_1608_p1 <= (0=>calo_8_hwIsEM_read, others=>'-');
    sel_tmp122_fu_1608_p2 <= (sel_tmp122_fu_1608_p1 and rev52_fu_1602_p2);
    sel_tmp123_fu_1614_p2 <= (sel_tmp122_fu_1608_p2 or rev51_fu_1590_p2);
    sel_tmp137_fu_1708_p1 <= (0=>calo_9_hwIsEM_read, others=>'-');
    sel_tmp137_fu_1708_p2 <= (sel_tmp137_fu_1708_p1 and rev54_fu_1702_p2);
    sel_tmp138_fu_1714_p2 <= (sel_tmp137_fu_1708_p2 or rev53_fu_1690_p2);
    sel_tmp152_fu_1808_p1 <= (0=>calo_10_hwIsEM_read, others=>'-');
    sel_tmp152_fu_1808_p2 <= (sel_tmp152_fu_1808_p1 and rev56_fu_1802_p2);
    sel_tmp153_fu_1814_p2 <= (sel_tmp152_fu_1808_p2 or rev55_fu_1790_p2);
    sel_tmp167_fu_1908_p1 <= (0=>calo_11_hwIsEM_read, others=>'-');
    sel_tmp167_fu_1908_p2 <= (sel_tmp167_fu_1908_p1 and rev58_fu_1902_p2);
    sel_tmp168_fu_1914_p2 <= (sel_tmp167_fu_1908_p2 or rev57_fu_1890_p2);
    sel_tmp17_fu_908_p1 <= (0=>calo_1_hwIsEM_read, others=>'-');
    sel_tmp17_fu_908_p2 <= (sel_tmp17_fu_908_p1 and rev38_fu_902_p2);
    sel_tmp182_fu_2008_p1 <= (0=>calo_12_hwIsEM_read, others=>'-');
    sel_tmp182_fu_2008_p2 <= (sel_tmp182_fu_2008_p1 and rev60_fu_2002_p2);
    sel_tmp183_fu_2014_p2 <= (sel_tmp182_fu_2008_p2 or rev59_fu_1990_p2);
    sel_tmp18_fu_914_p2 <= (sel_tmp17_fu_908_p2 or rev37_fu_890_p2);
    sel_tmp197_fu_2108_p1 <= (0=>calo_13_hwIsEM_read, others=>'-');
    sel_tmp197_fu_2108_p2 <= (sel_tmp197_fu_2108_p1 and rev62_fu_2102_p2);
    sel_tmp198_fu_2114_p2 <= (sel_tmp197_fu_2108_p2 or rev61_fu_2090_p2);
    sel_tmp212_fu_2208_p1 <= (0=>calo_14_hwIsEM_read, others=>'-');
    sel_tmp212_fu_2208_p2 <= (sel_tmp212_fu_2208_p1 and rev64_fu_2202_p2);
    sel_tmp213_fu_2214_p2 <= (sel_tmp212_fu_2208_p2 or rev63_fu_2190_p2);
    sel_tmp2_fu_808_p1 <= (0=>calo_0_hwIsEM_read, others=>'-');
    sel_tmp2_fu_808_p2 <= (sel_tmp2_fu_808_p1 and rev36_fu_802_p2);
    sel_tmp32_fu_1008_p1 <= (0=>calo_2_hwIsEM_read, others=>'-');
    sel_tmp32_fu_1008_p2 <= (sel_tmp32_fu_1008_p1 and rev40_fu_1002_p2);
    sel_tmp33_fu_1014_p2 <= (sel_tmp32_fu_1008_p2 or rev39_fu_990_p2);
    sel_tmp3_fu_814_p2 <= (sel_tmp2_fu_808_p2 or rev_fu_790_p2);
    sel_tmp47_fu_1108_p1 <= (0=>calo_3_hwIsEM_read, others=>'-');
    sel_tmp47_fu_1108_p2 <= (sel_tmp47_fu_1108_p1 and rev42_fu_1102_p2);
    sel_tmp48_fu_1114_p2 <= (sel_tmp47_fu_1108_p2 or rev41_fu_1090_p2);
    sel_tmp62_fu_1208_p1 <= (0=>calo_4_hwIsEM_read, others=>'-');
    sel_tmp62_fu_1208_p2 <= (sel_tmp62_fu_1208_p1 and rev44_fu_1202_p2);
    sel_tmp63_fu_1214_p2 <= (sel_tmp62_fu_1208_p2 or rev43_fu_1190_p2);
    sel_tmp77_fu_1308_p1 <= (0=>calo_5_hwIsEM_read, others=>'-');
    sel_tmp77_fu_1308_p2 <= (sel_tmp77_fu_1308_p1 and rev46_fu_1302_p2);
    sel_tmp78_fu_1314_p2 <= (sel_tmp77_fu_1308_p2 or rev45_fu_1290_p2);
    sel_tmp92_fu_1408_p1 <= (0=>calo_6_hwIsEM_read, others=>'-');
    sel_tmp92_fu_1408_p2 <= (sel_tmp92_fu_1408_p1 and rev48_fu_1402_p2);
    sel_tmp93_fu_1414_p2 <= (sel_tmp92_fu_1408_p2 or rev47_fu_1390_p2);
    slt36_fu_796_p2 <= "1" when (signed(r_V_9_fu_780_p1) < signed(emsub_V_fu_750_p2)) else "0";
    slt37_fu_884_p2 <= "1" when (signed(r_V_1_fu_866_p1) < signed(ptsub_V_1_fu_844_p2)) else "0";
    slt38_fu_896_p2 <= "1" when (signed(r_V_9_1_fu_880_p1) < signed(emsub_V_s_fu_850_p2)) else "0";
    slt39_fu_984_p2 <= "1" when (signed(r_V_2_fu_966_p1) < signed(ptsub_V_2_fu_944_p2)) else "0";
    slt40_fu_996_p2 <= "1" when (signed(r_V_9_2_fu_980_p1) < signed(emsub_V_2_fu_950_p2)) else "0";
    slt41_fu_1084_p2 <= "1" when (signed(r_V_3_fu_1066_p1) < signed(ptsub_V_3_fu_1044_p2)) else "0";
    slt42_fu_1096_p2 <= "1" when (signed(r_V_9_3_fu_1080_p1) < signed(emsub_V_3_fu_1050_p2)) else "0";
    slt43_fu_1184_p2 <= "1" when (signed(r_V_4_fu_1166_p1) < signed(ptsub_V_4_fu_1144_p2)) else "0";
    slt44_fu_1196_p2 <= "1" when (signed(r_V_9_4_fu_1180_p1) < signed(emsub_V_4_fu_1150_p2)) else "0";
    slt45_fu_1284_p2 <= "1" when (signed(r_V_5_fu_1266_p1) < signed(ptsub_V_5_fu_1244_p2)) else "0";
    slt46_fu_1296_p2 <= "1" when (signed(r_V_9_5_fu_1280_p1) < signed(emsub_V_5_fu_1250_p2)) else "0";
    slt47_fu_1384_p2 <= "1" when (signed(r_V_6_fu_1366_p1) < signed(ptsub_V_6_fu_1344_p2)) else "0";
    slt48_fu_1396_p2 <= "1" when (signed(r_V_9_6_fu_1380_p1) < signed(emsub_V_6_fu_1350_p2)) else "0";
    slt49_fu_1484_p2 <= "1" when (signed(r_V_7_fu_1466_p1) < signed(ptsub_V_7_fu_1444_p2)) else "0";
    slt50_fu_1496_p2 <= "1" when (signed(r_V_9_7_fu_1480_p1) < signed(emsub_V_7_fu_1450_p2)) else "0";
    slt51_fu_1584_p2 <= "1" when (signed(r_V_8_fu_1566_p1) < signed(ptsub_V_8_fu_1544_p2)) else "0";
    slt52_fu_1596_p2 <= "1" when (signed(r_V_9_8_fu_1580_p1) < signed(emsub_V_8_fu_1550_p2)) else "0";
    slt53_fu_1684_p2 <= "1" when (signed(r_V_s_fu_1666_p1) < signed(ptsub_V_9_fu_1644_p2)) else "0";
    slt54_fu_1696_p2 <= "1" when (signed(r_V_9_9_fu_1680_p1) < signed(emsub_V_9_fu_1650_p2)) else "0";
    slt55_fu_1784_p2 <= "1" when (signed(r_V_10_fu_1766_p1) < signed(ptsub_V_s_fu_1744_p2)) else "0";
    slt56_fu_1796_p2 <= "1" when (signed(r_V_9_s_fu_1780_p1) < signed(emsub_V_1_fu_1750_p2)) else "0";
    slt57_fu_1884_p2 <= "1" when (signed(r_V_11_fu_1866_p1) < signed(ptsub_V_10_fu_1844_p2)) else "0";
    slt58_fu_1896_p2 <= "1" when (signed(r_V_9_10_fu_1880_p1) < signed(emsub_V_10_fu_1850_p2)) else "0";
    slt59_fu_1984_p2 <= "1" when (signed(r_V_12_fu_1966_p1) < signed(ptsub_V_11_fu_1944_p2)) else "0";
    slt60_fu_1996_p2 <= "1" when (signed(r_V_9_11_fu_1980_p1) < signed(emsub_V_11_fu_1950_p2)) else "0";
    slt61_fu_2084_p2 <= "1" when (signed(r_V_13_fu_2066_p1) < signed(ptsub_V_12_fu_2044_p2)) else "0";
    slt62_fu_2096_p2 <= "1" when (signed(r_V_9_12_fu_2080_p1) < signed(emsub_V_12_fu_2050_p2)) else "0";
    slt63_fu_2184_p2 <= "1" when (signed(r_V_14_fu_2166_p1) < signed(ptsub_V_13_fu_2144_p2)) else "0";
    slt64_fu_2196_p2 <= "1" when (signed(r_V_9_13_fu_2180_p1) < signed(emsub_V_13_fu_2150_p2)) else "0";
    slt_fu_784_p2 <= "1" when (signed(r_V_fu_766_p1) < signed(ptsub_V_fu_744_p2)) else "0";
    tmp_108_fu_770_p4 <= calo_0_hwEmPt_V_rea(15 downto 3);
    tmp_109_fu_856_p4 <= calo_1_hwPt_V_read(15 downto 4);
    tmp_110_fu_870_p4 <= calo_1_hwEmPt_V_rea(15 downto 3);
    tmp_111_fu_956_p4 <= calo_2_hwPt_V_read(15 downto 4);
    tmp_112_fu_970_p4 <= calo_2_hwEmPt_V_rea(15 downto 3);
    tmp_113_fu_1056_p4 <= calo_3_hwPt_V_read(15 downto 4);
    tmp_114_fu_1070_p4 <= calo_3_hwEmPt_V_rea(15 downto 3);
    tmp_115_fu_1156_p4 <= calo_4_hwPt_V_read(15 downto 4);
    tmp_116_fu_1170_p4 <= calo_4_hwEmPt_V_rea(15 downto 3);
    tmp_117_fu_1256_p4 <= calo_5_hwPt_V_read(15 downto 4);
    tmp_118_fu_1270_p4 <= calo_5_hwEmPt_V_rea(15 downto 3);
    tmp_119_fu_1356_p4 <= calo_6_hwPt_V_read(15 downto 4);
    tmp_120_fu_1370_p4 <= calo_6_hwEmPt_V_rea(15 downto 3);
    tmp_121_fu_1456_p4 <= calo_7_hwPt_V_read(15 downto 4);
    tmp_122_fu_1470_p4 <= calo_7_hwEmPt_V_rea(15 downto 3);
    tmp_123_fu_1556_p4 <= calo_8_hwPt_V_read(15 downto 4);
    tmp_124_fu_1570_p4 <= calo_8_hwEmPt_V_rea(15 downto 3);
    tmp_125_fu_1656_p4 <= calo_9_hwPt_V_read(15 downto 4);
    tmp_126_fu_1670_p4 <= calo_9_hwEmPt_V_rea(15 downto 3);
    tmp_127_fu_1756_p4 <= calo_10_hwPt_V_read(15 downto 4);
    tmp_128_fu_1770_p4 <= calo_10_hwEmPt_V_re(15 downto 3);
    tmp_129_fu_1856_p4 <= calo_11_hwPt_V_read(15 downto 4);
    tmp_130_fu_1870_p4 <= calo_11_hwEmPt_V_re(15 downto 3);
    tmp_131_fu_1956_p4 <= calo_12_hwPt_V_read(15 downto 4);
    tmp_132_fu_1970_p4 <= calo_12_hwEmPt_V_re(15 downto 3);
    tmp_133_fu_2056_p4 <= calo_13_hwPt_V_read(15 downto 4);
    tmp_134_fu_2070_p4 <= calo_13_hwEmPt_V_re(15 downto 3);
    tmp_135_fu_2156_p4 <= calo_14_hwPt_V_read(15 downto 4);
    tmp_136_fu_2170_p4 <= calo_14_hwEmPt_V_re(15 downto 3);
    tmp_s_fu_756_p4 <= calo_0_hwPt_V_read(15 downto 4);
end behav;
