-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity tk2calo_drdptvalsjbC_rom is 
    generic(
             dwidth     : integer := 17; 
             awidth     : integer := 9; 
             mem_size    : integer := 512
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          addr1      : in std_logic_vector(awidth-1 downto 0); 
          ce1       : in std_logic; 
          q1         : out std_logic_vector(dwidth-1 downto 0);
          addr2      : in std_logic_vector(awidth-1 downto 0); 
          ce2       : in std_logic; 
          q2         : out std_logic_vector(dwidth-1 downto 0);
          addr3      : in std_logic_vector(awidth-1 downto 0); 
          ce3       : in std_logic; 
          q3         : out std_logic_vector(dwidth-1 downto 0);
          addr4      : in std_logic_vector(awidth-1 downto 0); 
          ce4       : in std_logic; 
          q4         : out std_logic_vector(dwidth-1 downto 0);
          addr5      : in std_logic_vector(awidth-1 downto 0); 
          ce5       : in std_logic; 
          q5         : out std_logic_vector(dwidth-1 downto 0);
          addr6      : in std_logic_vector(awidth-1 downto 0); 
          ce6       : in std_logic; 
          q6         : out std_logic_vector(dwidth-1 downto 0);
          addr7      : in std_logic_vector(awidth-1 downto 0); 
          ce7       : in std_logic; 
          q7         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of tk2calo_drdptvalsjbC_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
signal addr1_tmp : std_logic_vector(awidth-1 downto 0); 
signal addr2_tmp : std_logic_vector(awidth-1 downto 0); 
signal addr3_tmp : std_logic_vector(awidth-1 downto 0); 
signal addr4_tmp : std_logic_vector(awidth-1 downto 0); 
signal addr5_tmp : std_logic_vector(awidth-1 downto 0); 
signal addr6_tmp : std_logic_vector(awidth-1 downto 0); 
signal addr7_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem0 : mem_array := (
    0 to 1=> "10111100100000000", 2 => "00101111001000000", 
    3 => "00010100111100011", 4 => "00001011110010000", 
    5 => "00000111100010100", 6 => "00000101001111000", 
    7 => "00000011110110001", 8 => "00000010111100100", 
    9 => "00000010010100111", 10 => "00000001111000101", 
    11 => "00000001100011101", 12 => "00000001010011110", 
    13 => "00000001000111011", 14 => "00000000111101100", 
    15 => "00000000110101100", 16 => "00000000101111001", 
    17 => "00000000101001101", 18 => "00000000100101001", 
    19 => "00000000100001011", 20 => "00000000011110001", 
    21 => "00000000011011010", 22 => "00000000011000111", 
    23 => "00000000010110110", 24 => "00000000010100111", 
    25 => "00000000010011010", 26 => "00000000010001110", 
    27 => "00000000010000100", 28 => "00000000001111011", 
    29 => "00000000001110010", 30 => "00000000001101011", 
    31 => "00000000001100100", 32 => "00000000001011110", 
    33 => "00000000001011000", 34 => "00000000001010011", 
    35 => "00000000001001110", 36 => "00000000001001010", 
    37 => "00000000001000110", 38 => "00000000001000010", 
    39 => "00000000000111111", 40 => "00000000000111100", 
    41 => "00000000000111001", 42 => "00000000000110110", 
    43 => "00000000000110100", 44 => "00000000000110001", 
    45 => "00000000000101111", 46 => "00000000000101101", 
    47 => "00000000000101011", 48 => "00000000000101001", 
    49 => "00000000000101000", 50 => "00000000000100110", 
    51 => "00000000000100101", 52 => "00000000000100011", 
    53 => "00000000000100010", 54 => "00000000000100001", 
    55 => "00000000000011111", 56 => "00000000000011110", 
    57 => "00000000000011101", 58 => "00000000000011100", 
    59 => "00000000000011011", 60 => "00000000000011010", 
    61 to 62=> "00000000000011001", 63 => "00000000000011000", 
    64 => "00000000000010111", 65 to 66=> "00000000000010110", 
    67 => "00000000000010101", 68 to 69=> "00000000000010100", 
    70 to 71=> "00000000000010011", 72 to 73=> "00000000000010010", 
    74 to 75=> "00000000000010001", 76 to 77=> "00000000000010000", 
    78 to 80=> "00000000000001111", 81 to 83=> "00000000000001110", 
    84 to 86=> "00000000000001101", 87 to 89=> "00000000000001100", 
    90 to 93=> "00000000000001011", 94 to 98=> "00000000000001010", 
    99 to 103=> "00000000000001001", 104 to 109=> "00000000000001000", 
    110 to 117=> "00000000000000111", 118 to 126=> "00000000000000110", 
    127 to 138=> "00000000000000101", 139 to 155=> "00000000000000100", 
    156 to 179=> "00000000000000011", 180 to 219=> "00000000000000010", 
    220 to 310=> "00000000000000001", 311 to 511=> "00000000000000000" );
signal mem1 : mem_array := (
    0 to 1=> "10111100100000000", 2 => "00101111001000000", 
    3 => "00010100111100011", 4 => "00001011110010000", 
    5 => "00000111100010100", 6 => "00000101001111000", 
    7 => "00000011110110001", 8 => "00000010111100100", 
    9 => "00000010010100111", 10 => "00000001111000101", 
    11 => "00000001100011101", 12 => "00000001010011110", 
    13 => "00000001000111011", 14 => "00000000111101100", 
    15 => "00000000110101100", 16 => "00000000101111001", 
    17 => "00000000101001101", 18 => "00000000100101001", 
    19 => "00000000100001011", 20 => "00000000011110001", 
    21 => "00000000011011010", 22 => "00000000011000111", 
    23 => "00000000010110110", 24 => "00000000010100111", 
    25 => "00000000010011010", 26 => "00000000010001110", 
    27 => "00000000010000100", 28 => "00000000001111011", 
    29 => "00000000001110010", 30 => "00000000001101011", 
    31 => "00000000001100100", 32 => "00000000001011110", 
    33 => "00000000001011000", 34 => "00000000001010011", 
    35 => "00000000001001110", 36 => "00000000001001010", 
    37 => "00000000001000110", 38 => "00000000001000010", 
    39 => "00000000000111111", 40 => "00000000000111100", 
    41 => "00000000000111001", 42 => "00000000000110110", 
    43 => "00000000000110100", 44 => "00000000000110001", 
    45 => "00000000000101111", 46 => "00000000000101101", 
    47 => "00000000000101011", 48 => "00000000000101001", 
    49 => "00000000000101000", 50 => "00000000000100110", 
    51 => "00000000000100101", 52 => "00000000000100011", 
    53 => "00000000000100010", 54 => "00000000000100001", 
    55 => "00000000000011111", 56 => "00000000000011110", 
    57 => "00000000000011101", 58 => "00000000000011100", 
    59 => "00000000000011011", 60 => "00000000000011010", 
    61 to 62=> "00000000000011001", 63 => "00000000000011000", 
    64 => "00000000000010111", 65 to 66=> "00000000000010110", 
    67 => "00000000000010101", 68 to 69=> "00000000000010100", 
    70 to 71=> "00000000000010011", 72 to 73=> "00000000000010010", 
    74 to 75=> "00000000000010001", 76 to 77=> "00000000000010000", 
    78 to 80=> "00000000000001111", 81 to 83=> "00000000000001110", 
    84 to 86=> "00000000000001101", 87 to 89=> "00000000000001100", 
    90 to 93=> "00000000000001011", 94 to 98=> "00000000000001010", 
    99 to 103=> "00000000000001001", 104 to 109=> "00000000000001000", 
    110 to 117=> "00000000000000111", 118 to 126=> "00000000000000110", 
    127 to 138=> "00000000000000101", 139 to 155=> "00000000000000100", 
    156 to 179=> "00000000000000011", 180 to 219=> "00000000000000010", 
    220 to 310=> "00000000000000001", 311 to 511=> "00000000000000000" );
signal mem2 : mem_array := (
    0 to 1=> "10111100100000000", 2 => "00101111001000000", 
    3 => "00010100111100011", 4 => "00001011110010000", 
    5 => "00000111100010100", 6 => "00000101001111000", 
    7 => "00000011110110001", 8 => "00000010111100100", 
    9 => "00000010010100111", 10 => "00000001111000101", 
    11 => "00000001100011101", 12 => "00000001010011110", 
    13 => "00000001000111011", 14 => "00000000111101100", 
    15 => "00000000110101100", 16 => "00000000101111001", 
    17 => "00000000101001101", 18 => "00000000100101001", 
    19 => "00000000100001011", 20 => "00000000011110001", 
    21 => "00000000011011010", 22 => "00000000011000111", 
    23 => "00000000010110110", 24 => "00000000010100111", 
    25 => "00000000010011010", 26 => "00000000010001110", 
    27 => "00000000010000100", 28 => "00000000001111011", 
    29 => "00000000001110010", 30 => "00000000001101011", 
    31 => "00000000001100100", 32 => "00000000001011110", 
    33 => "00000000001011000", 34 => "00000000001010011", 
    35 => "00000000001001110", 36 => "00000000001001010", 
    37 => "00000000001000110", 38 => "00000000001000010", 
    39 => "00000000000111111", 40 => "00000000000111100", 
    41 => "00000000000111001", 42 => "00000000000110110", 
    43 => "00000000000110100", 44 => "00000000000110001", 
    45 => "00000000000101111", 46 => "00000000000101101", 
    47 => "00000000000101011", 48 => "00000000000101001", 
    49 => "00000000000101000", 50 => "00000000000100110", 
    51 => "00000000000100101", 52 => "00000000000100011", 
    53 => "00000000000100010", 54 => "00000000000100001", 
    55 => "00000000000011111", 56 => "00000000000011110", 
    57 => "00000000000011101", 58 => "00000000000011100", 
    59 => "00000000000011011", 60 => "00000000000011010", 
    61 to 62=> "00000000000011001", 63 => "00000000000011000", 
    64 => "00000000000010111", 65 to 66=> "00000000000010110", 
    67 => "00000000000010101", 68 to 69=> "00000000000010100", 
    70 to 71=> "00000000000010011", 72 to 73=> "00000000000010010", 
    74 to 75=> "00000000000010001", 76 to 77=> "00000000000010000", 
    78 to 80=> "00000000000001111", 81 to 83=> "00000000000001110", 
    84 to 86=> "00000000000001101", 87 to 89=> "00000000000001100", 
    90 to 93=> "00000000000001011", 94 to 98=> "00000000000001010", 
    99 to 103=> "00000000000001001", 104 to 109=> "00000000000001000", 
    110 to 117=> "00000000000000111", 118 to 126=> "00000000000000110", 
    127 to 138=> "00000000000000101", 139 to 155=> "00000000000000100", 
    156 to 179=> "00000000000000011", 180 to 219=> "00000000000000010", 
    220 to 310=> "00000000000000001", 311 to 511=> "00000000000000000" );
signal mem3 : mem_array := (
    0 to 1=> "10111100100000000", 2 => "00101111001000000", 
    3 => "00010100111100011", 4 => "00001011110010000", 
    5 => "00000111100010100", 6 => "00000101001111000", 
    7 => "00000011110110001", 8 => "00000010111100100", 
    9 => "00000010010100111", 10 => "00000001111000101", 
    11 => "00000001100011101", 12 => "00000001010011110", 
    13 => "00000001000111011", 14 => "00000000111101100", 
    15 => "00000000110101100", 16 => "00000000101111001", 
    17 => "00000000101001101", 18 => "00000000100101001", 
    19 => "00000000100001011", 20 => "00000000011110001", 
    21 => "00000000011011010", 22 => "00000000011000111", 
    23 => "00000000010110110", 24 => "00000000010100111", 
    25 => "00000000010011010", 26 => "00000000010001110", 
    27 => "00000000010000100", 28 => "00000000001111011", 
    29 => "00000000001110010", 30 => "00000000001101011", 
    31 => "00000000001100100", 32 => "00000000001011110", 
    33 => "00000000001011000", 34 => "00000000001010011", 
    35 => "00000000001001110", 36 => "00000000001001010", 
    37 => "00000000001000110", 38 => "00000000001000010", 
    39 => "00000000000111111", 40 => "00000000000111100", 
    41 => "00000000000111001", 42 => "00000000000110110", 
    43 => "00000000000110100", 44 => "00000000000110001", 
    45 => "00000000000101111", 46 => "00000000000101101", 
    47 => "00000000000101011", 48 => "00000000000101001", 
    49 => "00000000000101000", 50 => "00000000000100110", 
    51 => "00000000000100101", 52 => "00000000000100011", 
    53 => "00000000000100010", 54 => "00000000000100001", 
    55 => "00000000000011111", 56 => "00000000000011110", 
    57 => "00000000000011101", 58 => "00000000000011100", 
    59 => "00000000000011011", 60 => "00000000000011010", 
    61 to 62=> "00000000000011001", 63 => "00000000000011000", 
    64 => "00000000000010111", 65 to 66=> "00000000000010110", 
    67 => "00000000000010101", 68 to 69=> "00000000000010100", 
    70 to 71=> "00000000000010011", 72 to 73=> "00000000000010010", 
    74 to 75=> "00000000000010001", 76 to 77=> "00000000000010000", 
    78 to 80=> "00000000000001111", 81 to 83=> "00000000000001110", 
    84 to 86=> "00000000000001101", 87 to 89=> "00000000000001100", 
    90 to 93=> "00000000000001011", 94 to 98=> "00000000000001010", 
    99 to 103=> "00000000000001001", 104 to 109=> "00000000000001000", 
    110 to 117=> "00000000000000111", 118 to 126=> "00000000000000110", 
    127 to 138=> "00000000000000101", 139 to 155=> "00000000000000100", 
    156 to 179=> "00000000000000011", 180 to 219=> "00000000000000010", 
    220 to 310=> "00000000000000001", 311 to 511=> "00000000000000000" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem0 : signal is "block_rom";
attribute syn_rom_style of mem1 : signal is "block_rom";
attribute syn_rom_style of mem2 : signal is "block_rom";
attribute syn_rom_style of mem3 : signal is "block_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem0 : signal is "block";
attribute ROM_STYLE of mem1 : signal is "block";
attribute ROM_STYLE of mem2 : signal is "block";
attribute ROM_STYLE of mem3 : signal is "block";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

memory_access_guard_1: process (addr1) 
begin
      addr1_tmp <= addr1;
--synthesis translate_off
      if (CONV_INTEGER(addr1) > mem_size-1) then
           addr1_tmp <= (others => '0');
      else 
           addr1_tmp <= addr1;
      end if;
--synthesis translate_on
end process;

memory_access_guard_2: process (addr2) 
begin
      addr2_tmp <= addr2;
--synthesis translate_off
      if (CONV_INTEGER(addr2) > mem_size-1) then
           addr2_tmp <= (others => '0');
      else 
           addr2_tmp <= addr2;
      end if;
--synthesis translate_on
end process;

memory_access_guard_3: process (addr3) 
begin
      addr3_tmp <= addr3;
--synthesis translate_off
      if (CONV_INTEGER(addr3) > mem_size-1) then
           addr3_tmp <= (others => '0');
      else 
           addr3_tmp <= addr3;
      end if;
--synthesis translate_on
end process;

memory_access_guard_4: process (addr4) 
begin
      addr4_tmp <= addr4;
--synthesis translate_off
      if (CONV_INTEGER(addr4) > mem_size-1) then
           addr4_tmp <= (others => '0');
      else 
           addr4_tmp <= addr4;
      end if;
--synthesis translate_on
end process;

memory_access_guard_5: process (addr5) 
begin
      addr5_tmp <= addr5;
--synthesis translate_off
      if (CONV_INTEGER(addr5) > mem_size-1) then
           addr5_tmp <= (others => '0');
      else 
           addr5_tmp <= addr5;
      end if;
--synthesis translate_on
end process;

memory_access_guard_6: process (addr6) 
begin
      addr6_tmp <= addr6;
--synthesis translate_off
      if (CONV_INTEGER(addr6) > mem_size-1) then
           addr6_tmp <= (others => '0');
      else 
           addr6_tmp <= addr6;
      end if;
--synthesis translate_on
end process;

memory_access_guard_7: process (addr7) 
begin
      addr7_tmp <= addr7;
--synthesis translate_off
      if (CONV_INTEGER(addr7) > mem_size-1) then
           addr7_tmp <= (others => '0');
      else 
           addr7_tmp <= addr7;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem0(CONV_INTEGER(addr0_tmp)); 
        end if;
        if (ce1 = '1') then 
            q1 <= mem0(CONV_INTEGER(addr1_tmp)); 
        end if;
        if (ce2 = '1') then 
            q2 <= mem1(CONV_INTEGER(addr2_tmp)); 
        end if;
        if (ce3 = '1') then 
            q3 <= mem1(CONV_INTEGER(addr3_tmp)); 
        end if;
        if (ce4 = '1') then 
            q4 <= mem2(CONV_INTEGER(addr4_tmp)); 
        end if;
        if (ce5 = '1') then 
            q5 <= mem2(CONV_INTEGER(addr5_tmp)); 
        end if;
        if (ce6 = '1') then 
            q6 <= mem3(CONV_INTEGER(addr6_tmp)); 
        end if;
        if (ce7 = '1') then 
            q7 <= mem3(CONV_INTEGER(addr7_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity tk2calo_drdptvalsjbC is
    generic (
        DataWidth : INTEGER := 17;
        AddressRange : INTEGER := 512;
        AddressWidth : INTEGER := 9);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        address1 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        address2 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        address3 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        address4 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        address5 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        address6 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce6 : IN STD_LOGIC;
        q6 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0);
        address7 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce7 : IN STD_LOGIC;
        q7 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of tk2calo_drdptvalsjbC is
    component tk2calo_drdptvalsjbC_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR;
            addr1 : IN STD_LOGIC_VECTOR;
            ce1 : IN STD_LOGIC;
            q1 : OUT STD_LOGIC_VECTOR;
            addr2 : IN STD_LOGIC_VECTOR;
            ce2 : IN STD_LOGIC;
            q2 : OUT STD_LOGIC_VECTOR;
            addr3 : IN STD_LOGIC_VECTOR;
            ce3 : IN STD_LOGIC;
            q3 : OUT STD_LOGIC_VECTOR;
            addr4 : IN STD_LOGIC_VECTOR;
            ce4 : IN STD_LOGIC;
            q4 : OUT STD_LOGIC_VECTOR;
            addr5 : IN STD_LOGIC_VECTOR;
            ce5 : IN STD_LOGIC;
            q5 : OUT STD_LOGIC_VECTOR;
            addr6 : IN STD_LOGIC_VECTOR;
            ce6 : IN STD_LOGIC;
            q6 : OUT STD_LOGIC_VECTOR;
            addr7 : IN STD_LOGIC_VECTOR;
            ce7 : IN STD_LOGIC;
            q7 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    tk2calo_drdptvalsjbC_rom_U :  component tk2calo_drdptvalsjbC_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0,
        addr1 => address1,
        ce1 => ce1,
        q1 => q1,
        addr2 => address2,
        ce2 => ce2,
        q2 => q2,
        addr3 => address3,
        ce3 => ce3,
        q3 => q3,
        addr4 => address4,
        ce4 => ce4,
        q4 => q4,
        addr5 => address5,
        ce5 => ce5,
        q5 => q5,
        addr6 => address6,
        ce6 => ce6,
        q6 => q6,
        addr7 => address7,
        ce7 => ce7,
        q7 => q7);

end architecture;


