-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tk2calo_caloalgo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    calo_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_10_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_11_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_12_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_13_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_14_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_10_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_11_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_12_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_13_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_14_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_10_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_11_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_12_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_13_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_14_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    sumtk_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_12_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtk_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumtkerr2_0_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_1_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_2_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_3_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_4_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_5_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_6_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_7_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_8_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_9_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_10_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_11_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_12_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_13_read : IN STD_LOGIC_VECTOR (31 downto 0);
    sumtkerr2_14_read : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_45 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_46 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_47 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_48 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_49 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_50 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_51 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_52 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_53 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_54 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_55 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_56 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_57 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_58 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_59 : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of tk2calo_caloalgo is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sumtk_14_V_read_2_reg_2857 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_13_V_read_2_reg_2862 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_12_V_read_2_reg_2867 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_11_V_read_2_reg_2872 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_10_V_read_2_reg_2877 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_9_V_read_2_reg_2882 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_8_V_read_2_reg_2887 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_0_hwPt_V_writ_fu_703_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_0_hwPt_V_writ_reg_2892 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_1_hwPt_V_writ_fu_792_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_1_hwPt_V_writ_reg_2899 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_2_hwPt_V_writ_fu_881_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_2_hwPt_V_writ_reg_2906 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_3_hwPt_V_writ_fu_970_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_3_hwPt_V_writ_reg_2913 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_4_hwPt_V_writ_fu_1059_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_4_hwPt_V_writ_reg_2920 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_5_hwPt_V_writ_fu_1148_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_5_hwPt_V_writ_reg_2927 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_6_hwPt_V_writ_fu_1237_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_6_hwPt_V_writ_reg_2934 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_7_hwPt_V_writ_fu_1326_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_7_hwPt_V_writ_reg_2941 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_1334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_2948 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_1340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_2954 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_1346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_2960 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_1352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_2966 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_1358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_2972 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_1364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_2978 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_53_fu_1370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_53_reg_2984 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_calo_8_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_calo_9_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_calo_10_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_calo_11_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_calo_12_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_calo_13_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_calo_14_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_calo_0_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_1_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_2_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_3_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_4_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_5_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_6_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_7_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_8_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_9_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_10_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_11_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_12_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_13_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_14_hwEta_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_0_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_1_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_2_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_3_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_4_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_5_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_6_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_7_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_8_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_9_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_10_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_11_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_12_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_13_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_14_hwPhi_V_rea : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_sumtkerr2_8_read : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_port_reg_sumtkerr2_9_read : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_port_reg_sumtkerr2_10_read : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_port_reg_sumtkerr2_11_read : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_port_reg_sumtkerr2_12_read : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_port_reg_sumtkerr2_13_read : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_port_reg_sumtkerr2_14_read : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal calopt_V_2_fu_628_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_22_fu_648_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_23_fu_658_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_2752_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_fu_662_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_673_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp75_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_685_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_634_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp3_fu_691_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp3_cast_fu_699_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal calopt_V_2_1_fu_717_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_27_fu_737_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_1_fu_747_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_1_fu_2759_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_1_fu_751_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_1_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp76_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_1_fu_727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_777_fu_723_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp8_fu_780_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp8_cast_fu_788_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal calopt_V_2_2_fu_806_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_28_fu_826_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_2_fu_836_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_fu_2766_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_2_fu_840_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_2_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp77_fu_857_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_2_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_863_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_778_fu_812_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp13_fu_869_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp13_cast_fu_877_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal calopt_V_2_3_fu_895_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_29_fu_915_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_3_fu_925_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_3_fu_2773_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_3_fu_929_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_889_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_3_fu_935_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp78_fu_946_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_3_fu_905_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_952_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_779_fu_901_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp18_fu_958_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp18_cast_fu_966_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal calopt_V_2_4_fu_984_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_30_fu_1004_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_4_fu_1014_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_4_fu_2780_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_4_fu_1018_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_978_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_4_fu_1024_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp20_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp79_fu_1035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_4_fu_994_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp22_fu_1041_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_780_fu_990_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp23_fu_1047_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp23_cast_fu_1055_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal calopt_V_2_5_fu_1073_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_31_fu_1093_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_5_fu_1103_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_5_fu_2787_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_5_fu_1107_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_1067_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_5_fu_1113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_fu_1118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp80_fu_1124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_5_fu_1083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp27_fu_1130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_781_fu_1079_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp28_fu_1136_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp28_cast_fu_1144_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal calopt_V_2_6_fu_1162_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_32_fu_1182_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_6_fu_1192_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_fu_2794_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_6_fu_1196_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_1156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_6_fu_1202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp30_fu_1207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp81_fu_1213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_6_fu_1172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_782_fu_1168_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp33_fu_1225_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp33_cast_fu_1233_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal calopt_V_2_7_fu_1251_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_fu_1271_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_7_fu_1281_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_7_fu_2801_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_7_fu_1285_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_1245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_7_fu_1291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp35_fu_1296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp82_fu_1302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_7_fu_1261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp37_fu_1308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_783_fu_1257_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp38_fu_1314_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp38_cast_fu_1322_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_25_fu_1376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_1397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_1_fu_1406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_1_fu_1427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_2_fu_1436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_2_fu_1457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_3_fu_1466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_3_fu_1487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_4_fu_1496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_4_fu_1517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_5_fu_1526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_5_fu_1547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_6_fu_1556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_6_fu_1577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_7_fu_1586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_7_fu_1607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calopt_V_2_8_fu_1616_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_34_fu_1635_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_8_fu_1645_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_8_fu_2808_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_8_fu_1649_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_32_8_fu_1655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp40_fu_1660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp83_fu_1665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_8_fu_1625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp42_fu_1671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_784_fu_1621_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp43_fu_1677_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp43_cast_fu_1685_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_8_hwPt_V_writ_fu_1689_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_8_fu_1696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_8_fu_1718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calopt_V_2_9_fu_1728_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_35_fu_1747_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_9_fu_1757_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_9_fu_2815_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_9_fu_1761_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_32_9_fu_1767_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp45_fu_1772_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp84_fu_1777_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_9_fu_1737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1783_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_785_fu_1733_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp48_fu_1789_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp48_cast_fu_1797_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_9_hwPt_V_writ_fu_1801_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_9_fu_1808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_9_fu_1830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calopt_V_2_s_fu_1840_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_36_fu_1859_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_s_fu_1869_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_10_fu_2822_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_s_fu_1873_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_32_s_fu_1879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp50_fu_1884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp85_fu_1889_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_s_fu_1849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp52_fu_1895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_786_fu_1845_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp53_fu_1901_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp53_cast_fu_1909_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_10_hwPt_V_wri_fu_1913_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_s_fu_1920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_s_fu_1942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calopt_V_2_10_fu_1952_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_37_fu_1971_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_10_fu_1981_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_11_fu_2829_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_10_fu_1985_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_32_10_fu_1991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp55_fu_1996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp86_fu_2001_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_10_fu_1961_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp57_fu_2007_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_787_fu_1957_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp58_fu_2013_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp58_cast_fu_2021_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_11_hwPt_V_wri_fu_2025_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_10_fu_2032_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_10_fu_2054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calopt_V_2_11_fu_2064_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_38_fu_2083_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_11_fu_2093_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_12_fu_2836_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_11_fu_2097_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_32_11_fu_2103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp60_fu_2108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp87_fu_2113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_11_fu_2073_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_2119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_788_fu_2069_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp63_fu_2125_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp63_cast_fu_2133_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_12_hwPt_V_wri_fu_2137_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_11_fu_2144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_11_fu_2166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calopt_V_2_12_fu_2176_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_39_fu_2195_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_12_fu_2205_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_13_fu_2843_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_12_fu_2209_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_32_12_fu_2215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp65_fu_2220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp88_fu_2225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_12_fu_2185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp67_fu_2231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_789_fu_2181_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp68_fu_2237_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp68_cast_fu_2245_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_13_hwPt_V_wri_fu_2249_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_12_fu_2256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_12_fu_2278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calopt_V_2_13_fu_2288_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_40_fu_2307_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_31_13_fu_2317_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_14_fu_2850_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_13_fu_2321_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_32_13_fu_2327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp70_fu_2332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp89_fu_2337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_13_fu_2297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp72_fu_2343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_790_fu_2293_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp73_fu_2349_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp73_cast_fu_2357_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_14_hwPt_V_wri_fu_2361_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_33_13_fu_2368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_13_fu_2390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_0_hwEta_V_read_2_fu_1381_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_1_hwEta_V_read_2_fu_1411_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_2_hwEta_V_read_2_fu_1441_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_3_hwEta_V_read_2_fu_1471_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_4_hwEta_V_read_2_fu_1501_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_5_hwEta_V_read_2_fu_1531_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_6_hwEta_V_read_2_fu_1561_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_7_hwEta_V_read_2_fu_1591_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_8_hwEta_V_read_2_fu_1702_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_9_hwEta_V_read_2_fu_1814_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_10_hwEta_V_rea_2_fu_1926_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_11_hwEta_V_rea_2_fu_2038_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_12_hwEta_V_rea_2_fu_2150_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_13_hwEta_V_rea_2_fu_2262_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_14_hwEta_V_rea_2_fu_2374_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_0_hwPhi_V_read_2_fu_1389_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_1_hwPhi_V_read_2_fu_1419_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_2_hwPhi_V_read_2_fu_1449_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_3_hwPhi_V_read_2_fu_1479_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_4_hwPhi_V_read_2_fu_1509_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_5_hwPhi_V_read_2_fu_1539_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_6_hwPhi_V_read_2_fu_1569_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_7_hwPhi_V_read_2_fu_1599_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_8_hwPhi_V_read_2_fu_1710_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_9_hwPhi_V_read_2_fu_1822_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_10_hwPhi_V_rea_2_fu_1934_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_11_hwPhi_V_rea_2_fu_2046_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_12_hwPhi_V_rea_2_fu_2158_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_13_hwPhi_V_rea_2_fu_2270_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_14_hwPhi_V_rea_2_fu_2382_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_0_hwId_V_writ_fu_1402_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_1_hwId_V_writ_fu_1432_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_2_hwId_V_writ_fu_1462_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_3_hwId_V_writ_fu_1492_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_4_hwId_V_writ_fu_1522_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_5_hwId_V_writ_fu_1552_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_6_hwId_V_writ_fu_1582_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_7_hwId_V_writ_fu_1612_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_8_hwId_V_writ_fu_1724_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_9_hwId_V_writ_fu_1836_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_10_hwId_V_wri_fu_1948_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_11_hwId_V_wri_fu_2060_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_12_hwId_V_wri_fu_2172_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_13_hwId_V_wri_fu_2284_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_14_hwId_V_wri_fu_2396_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_V_fu_2752_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_fu_644_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_2752_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_1_fu_2759_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_1_fu_733_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_1_fu_2759_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_2_fu_2766_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_2_fu_822_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_fu_2766_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_3_fu_2773_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_3_fu_911_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_3_fu_2773_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_4_fu_2780_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_4_fu_1000_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_4_fu_2780_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_5_fu_2787_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_5_fu_1089_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_5_fu_2787_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_6_fu_2794_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_6_fu_1178_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_fu_2794_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_7_fu_2801_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_7_fu_1267_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_7_fu_2801_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_8_fu_2808_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_8_fu_1631_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_8_fu_2808_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_fu_2815_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_9_fu_1743_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_9_fu_2815_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_10_fu_2822_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_10_fu_1855_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_10_fu_2822_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_11_fu_2829_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_11_fu_1967_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_11_fu_2829_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_12_fu_2836_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_12_fu_2079_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_12_fu_2836_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_13_fu_2843_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_13_fu_2191_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_13_fu_2843_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_14_fu_2850_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_V_14_fu_2303_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_14_fu_2850_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component mp7wrapped_pfalgokbM IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mp7wrapped_pfalgokbM_U2021 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_fu_2752_p0,
        din1 => r_V_fu_2752_p1,
        dout => r_V_fu_2752_p2);

    mp7wrapped_pfalgokbM_U2022 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_1_fu_2759_p0,
        din1 => r_V_1_fu_2759_p1,
        dout => r_V_1_fu_2759_p2);

    mp7wrapped_pfalgokbM_U2023 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_2_fu_2766_p0,
        din1 => r_V_2_fu_2766_p1,
        dout => r_V_2_fu_2766_p2);

    mp7wrapped_pfalgokbM_U2024 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_3_fu_2773_p0,
        din1 => r_V_3_fu_2773_p1,
        dout => r_V_3_fu_2773_p2);

    mp7wrapped_pfalgokbM_U2025 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_4_fu_2780_p0,
        din1 => r_V_4_fu_2780_p1,
        dout => r_V_4_fu_2780_p2);

    mp7wrapped_pfalgokbM_U2026 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_5_fu_2787_p0,
        din1 => r_V_5_fu_2787_p1,
        dout => r_V_5_fu_2787_p2);

    mp7wrapped_pfalgokbM_U2027 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_6_fu_2794_p0,
        din1 => r_V_6_fu_2794_p1,
        dout => r_V_6_fu_2794_p2);

    mp7wrapped_pfalgokbM_U2028 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_7_fu_2801_p0,
        din1 => r_V_7_fu_2801_p1,
        dout => r_V_7_fu_2801_p2);

    mp7wrapped_pfalgokbM_U2029 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_8_fu_2808_p0,
        din1 => r_V_8_fu_2808_p1,
        dout => r_V_8_fu_2808_p2);

    mp7wrapped_pfalgokbM_U2030 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_9_fu_2815_p0,
        din1 => r_V_9_fu_2815_p1,
        dout => r_V_9_fu_2815_p2);

    mp7wrapped_pfalgokbM_U2031 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_10_fu_2822_p0,
        din1 => r_V_10_fu_2822_p1,
        dout => r_V_10_fu_2822_p2);

    mp7wrapped_pfalgokbM_U2032 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_11_fu_2829_p0,
        din1 => r_V_11_fu_2829_p1,
        dout => r_V_11_fu_2829_p2);

    mp7wrapped_pfalgokbM_U2033 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_12_fu_2836_p0,
        din1 => r_V_12_fu_2836_p1,
        dout => r_V_12_fu_2836_p2);

    mp7wrapped_pfalgokbM_U2034 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_13_fu_2843_p0,
        din1 => r_V_13_fu_2843_p1,
        dout => r_V_13_fu_2843_p2);

    mp7wrapped_pfalgokbM_U2035 : component mp7wrapped_pfalgokbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => r_V_14_fu_2850_p0,
        din1 => r_V_14_fu_2850_p1,
        dout => r_V_14_fu_2850_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ap_port_reg_calo_0_hwEta_V_read <= calo_0_hwEta_V_read;
                ap_port_reg_calo_0_hwPhi_V_read <= calo_0_hwPhi_V_read;
                ap_port_reg_calo_10_hwEta_V_rea <= calo_10_hwEta_V_rea;
                ap_port_reg_calo_10_hwPhi_V_rea <= calo_10_hwPhi_V_rea;
                ap_port_reg_calo_10_hwPt_V_read <= calo_10_hwPt_V_read;
                ap_port_reg_calo_11_hwEta_V_rea <= calo_11_hwEta_V_rea;
                ap_port_reg_calo_11_hwPhi_V_rea <= calo_11_hwPhi_V_rea;
                ap_port_reg_calo_11_hwPt_V_read <= calo_11_hwPt_V_read;
                ap_port_reg_calo_12_hwEta_V_rea <= calo_12_hwEta_V_rea;
                ap_port_reg_calo_12_hwPhi_V_rea <= calo_12_hwPhi_V_rea;
                ap_port_reg_calo_12_hwPt_V_read <= calo_12_hwPt_V_read;
                ap_port_reg_calo_13_hwEta_V_rea <= calo_13_hwEta_V_rea;
                ap_port_reg_calo_13_hwPhi_V_rea <= calo_13_hwPhi_V_rea;
                ap_port_reg_calo_13_hwPt_V_read <= calo_13_hwPt_V_read;
                ap_port_reg_calo_14_hwEta_V_rea <= calo_14_hwEta_V_rea;
                ap_port_reg_calo_14_hwPhi_V_rea <= calo_14_hwPhi_V_rea;
                ap_port_reg_calo_14_hwPt_V_read <= calo_14_hwPt_V_read;
                ap_port_reg_calo_1_hwEta_V_read <= calo_1_hwEta_V_read;
                ap_port_reg_calo_1_hwPhi_V_read <= calo_1_hwPhi_V_read;
                ap_port_reg_calo_2_hwEta_V_read <= calo_2_hwEta_V_read;
                ap_port_reg_calo_2_hwPhi_V_read <= calo_2_hwPhi_V_read;
                ap_port_reg_calo_3_hwEta_V_read <= calo_3_hwEta_V_read;
                ap_port_reg_calo_3_hwPhi_V_read <= calo_3_hwPhi_V_read;
                ap_port_reg_calo_4_hwEta_V_read <= calo_4_hwEta_V_read;
                ap_port_reg_calo_4_hwPhi_V_read <= calo_4_hwPhi_V_read;
                ap_port_reg_calo_5_hwEta_V_read <= calo_5_hwEta_V_read;
                ap_port_reg_calo_5_hwPhi_V_read <= calo_5_hwPhi_V_read;
                ap_port_reg_calo_6_hwEta_V_read <= calo_6_hwEta_V_read;
                ap_port_reg_calo_6_hwPhi_V_read <= calo_6_hwPhi_V_read;
                ap_port_reg_calo_7_hwEta_V_read <= calo_7_hwEta_V_read;
                ap_port_reg_calo_7_hwPhi_V_read <= calo_7_hwPhi_V_read;
                ap_port_reg_calo_8_hwEta_V_read <= calo_8_hwEta_V_read;
                ap_port_reg_calo_8_hwPhi_V_read <= calo_8_hwPhi_V_read;
                ap_port_reg_calo_8_hwPt_V_read <= calo_8_hwPt_V_read;
                ap_port_reg_calo_9_hwEta_V_read <= calo_9_hwEta_V_read;
                ap_port_reg_calo_9_hwPhi_V_read <= calo_9_hwPhi_V_read;
                ap_port_reg_calo_9_hwPt_V_read <= calo_9_hwPt_V_read;
                ap_port_reg_sumtkerr2_10_read <= sumtkerr2_10_read;
                ap_port_reg_sumtkerr2_11_read <= sumtkerr2_11_read;
                ap_port_reg_sumtkerr2_12_read <= sumtkerr2_12_read;
                ap_port_reg_sumtkerr2_13_read <= sumtkerr2_13_read;
                ap_port_reg_sumtkerr2_14_read <= sumtkerr2_14_read;
                ap_port_reg_sumtkerr2_8_read <= sumtkerr2_8_read;
                ap_port_reg_sumtkerr2_9_read <= sumtkerr2_9_read;
                pfout_0_hwPt_V_writ_reg_2892 <= pfout_0_hwPt_V_writ_fu_703_p3;
                pfout_1_hwPt_V_writ_reg_2899 <= pfout_1_hwPt_V_writ_fu_792_p3;
                pfout_2_hwPt_V_writ_reg_2906 <= pfout_2_hwPt_V_writ_fu_881_p3;
                pfout_3_hwPt_V_writ_reg_2913 <= pfout_3_hwPt_V_writ_fu_970_p3;
                pfout_4_hwPt_V_writ_reg_2920 <= pfout_4_hwPt_V_writ_fu_1059_p3;
                pfout_5_hwPt_V_writ_reg_2927 <= pfout_5_hwPt_V_writ_fu_1148_p3;
                pfout_6_hwPt_V_writ_reg_2934 <= pfout_6_hwPt_V_writ_fu_1237_p3;
                pfout_7_hwPt_V_writ_reg_2941 <= pfout_7_hwPt_V_writ_fu_1326_p3;
                sumtk_10_V_read_2_reg_2877 <= sumtk_10_V_read;
                sumtk_11_V_read_2_reg_2872 <= sumtk_11_V_read;
                sumtk_12_V_read_2_reg_2867 <= sumtk_12_V_read;
                sumtk_13_V_read_2_reg_2862 <= sumtk_13_V_read;
                sumtk_14_V_read_2_reg_2857 <= sumtk_14_V_read;
                sumtk_8_V_read_2_reg_2887 <= sumtk_8_V_read;
                sumtk_9_V_read_2_reg_2882 <= sumtk_9_V_read;
                tmp_10_reg_2960 <= tmp_10_fu_1346_p2;
                tmp_11_reg_2966 <= tmp_11_fu_1352_p2;
                tmp_12_reg_2972 <= tmp_12_fu_1358_p2;
                tmp_13_reg_2978 <= tmp_13_fu_1364_p2;
                tmp_8_reg_2948 <= tmp_8_fu_1334_p2;
                tmp_9_reg_2954 <= tmp_9_fu_1340_p2;
                tmp_s_53_reg_2984 <= tmp_s_53_fu_1370_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= pfout_0_hwPt_V_writ_reg_2892;
    ap_return_1 <= pfout_1_hwPt_V_writ_reg_2899;
    ap_return_10 <= pfout_10_hwPt_V_wri_fu_1913_p3;
    ap_return_11 <= pfout_11_hwPt_V_wri_fu_2025_p3;
    ap_return_12 <= pfout_12_hwPt_V_wri_fu_2137_p3;
    ap_return_13 <= pfout_13_hwPt_V_wri_fu_2249_p3;
    ap_return_14 <= pfout_14_hwPt_V_wri_fu_2361_p3;
    ap_return_15 <= calo_0_hwEta_V_read_2_fu_1381_p3;
    ap_return_16 <= calo_1_hwEta_V_read_2_fu_1411_p3;
    ap_return_17 <= calo_2_hwEta_V_read_2_fu_1441_p3;
    ap_return_18 <= calo_3_hwEta_V_read_2_fu_1471_p3;
    ap_return_19 <= calo_4_hwEta_V_read_2_fu_1501_p3;
    ap_return_2 <= pfout_2_hwPt_V_writ_reg_2906;
    ap_return_20 <= calo_5_hwEta_V_read_2_fu_1531_p3;
    ap_return_21 <= calo_6_hwEta_V_read_2_fu_1561_p3;
    ap_return_22 <= calo_7_hwEta_V_read_2_fu_1591_p3;
    ap_return_23 <= calo_8_hwEta_V_read_2_fu_1702_p3;
    ap_return_24 <= calo_9_hwEta_V_read_2_fu_1814_p3;
    ap_return_25 <= calo_10_hwEta_V_rea_2_fu_1926_p3;
    ap_return_26 <= calo_11_hwEta_V_rea_2_fu_2038_p3;
    ap_return_27 <= calo_12_hwEta_V_rea_2_fu_2150_p3;
    ap_return_28 <= calo_13_hwEta_V_rea_2_fu_2262_p3;
    ap_return_29 <= calo_14_hwEta_V_rea_2_fu_2374_p3;
    ap_return_3 <= pfout_3_hwPt_V_writ_reg_2913;
    ap_return_30 <= calo_0_hwPhi_V_read_2_fu_1389_p3;
    ap_return_31 <= calo_1_hwPhi_V_read_2_fu_1419_p3;
    ap_return_32 <= calo_2_hwPhi_V_read_2_fu_1449_p3;
    ap_return_33 <= calo_3_hwPhi_V_read_2_fu_1479_p3;
    ap_return_34 <= calo_4_hwPhi_V_read_2_fu_1509_p3;
    ap_return_35 <= calo_5_hwPhi_V_read_2_fu_1539_p3;
    ap_return_36 <= calo_6_hwPhi_V_read_2_fu_1569_p3;
    ap_return_37 <= calo_7_hwPhi_V_read_2_fu_1599_p3;
    ap_return_38 <= calo_8_hwPhi_V_read_2_fu_1710_p3;
    ap_return_39 <= calo_9_hwPhi_V_read_2_fu_1822_p3;
    ap_return_4 <= pfout_4_hwPt_V_writ_reg_2920;
    ap_return_40 <= calo_10_hwPhi_V_rea_2_fu_1934_p3;
    ap_return_41 <= calo_11_hwPhi_V_rea_2_fu_2046_p3;
    ap_return_42 <= calo_12_hwPhi_V_rea_2_fu_2158_p3;
    ap_return_43 <= calo_13_hwPhi_V_rea_2_fu_2270_p3;
    ap_return_44 <= calo_14_hwPhi_V_rea_2_fu_2382_p3;
    ap_return_45 <= pfout_0_hwId_V_writ_fu_1402_p1;
    ap_return_46 <= pfout_1_hwId_V_writ_fu_1432_p1;
    ap_return_47 <= pfout_2_hwId_V_writ_fu_1462_p1;
    ap_return_48 <= pfout_3_hwId_V_writ_fu_1492_p1;
    ap_return_49 <= pfout_4_hwId_V_writ_fu_1522_p1;
    ap_return_5 <= pfout_5_hwPt_V_writ_reg_2927;
    ap_return_50 <= pfout_5_hwId_V_writ_fu_1552_p1;
    ap_return_51 <= pfout_6_hwId_V_writ_fu_1582_p1;
    ap_return_52 <= pfout_7_hwId_V_writ_fu_1612_p1;
    ap_return_53 <= pfout_8_hwId_V_writ_fu_1724_p1;
    ap_return_54 <= pfout_9_hwId_V_writ_fu_1836_p1;
    ap_return_55 <= pfout_10_hwId_V_wri_fu_1948_p1;
    ap_return_56 <= pfout_11_hwId_V_wri_fu_2060_p1;
    ap_return_57 <= pfout_12_hwId_V_wri_fu_2172_p1;
    ap_return_58 <= pfout_13_hwId_V_wri_fu_2284_p1;
    ap_return_59 <= pfout_14_hwId_V_wri_fu_2396_p1;
    ap_return_6 <= pfout_6_hwPt_V_writ_reg_2934;
    ap_return_7 <= pfout_7_hwPt_V_writ_reg_2941;
    ap_return_8 <= pfout_8_hwPt_V_writ_fu_1689_p3;
    ap_return_9 <= pfout_9_hwPt_V_writ_fu_1801_p3;
    calo_0_hwEta_V_read_2_fu_1381_p3 <= 
        ap_const_lv10_0 when (tmp_25_fu_1376_p2(0) = '1') else 
        ap_port_reg_calo_0_hwEta_V_read;
    calo_0_hwPhi_V_read_2_fu_1389_p3 <= 
        ap_const_lv10_0 when (tmp_25_fu_1376_p2(0) = '1') else 
        ap_port_reg_calo_0_hwPhi_V_read;
    calo_10_hwEta_V_rea_2_fu_1926_p3 <= 
        ap_const_lv10_0 when (tmp_33_s_fu_1920_p2(0) = '1') else 
        ap_port_reg_calo_10_hwEta_V_rea;
    calo_10_hwPhi_V_rea_2_fu_1934_p3 <= 
        ap_const_lv10_0 when (tmp_33_s_fu_1920_p2(0) = '1') else 
        ap_port_reg_calo_10_hwPhi_V_rea;
    calo_11_hwEta_V_rea_2_fu_2038_p3 <= 
        ap_const_lv10_0 when (tmp_33_10_fu_2032_p2(0) = '1') else 
        ap_port_reg_calo_11_hwEta_V_rea;
    calo_11_hwPhi_V_rea_2_fu_2046_p3 <= 
        ap_const_lv10_0 when (tmp_33_10_fu_2032_p2(0) = '1') else 
        ap_port_reg_calo_11_hwPhi_V_rea;
    calo_12_hwEta_V_rea_2_fu_2150_p3 <= 
        ap_const_lv10_0 when (tmp_33_11_fu_2144_p2(0) = '1') else 
        ap_port_reg_calo_12_hwEta_V_rea;
    calo_12_hwPhi_V_rea_2_fu_2158_p3 <= 
        ap_const_lv10_0 when (tmp_33_11_fu_2144_p2(0) = '1') else 
        ap_port_reg_calo_12_hwPhi_V_rea;
    calo_13_hwEta_V_rea_2_fu_2262_p3 <= 
        ap_const_lv10_0 when (tmp_33_12_fu_2256_p2(0) = '1') else 
        ap_port_reg_calo_13_hwEta_V_rea;
    calo_13_hwPhi_V_rea_2_fu_2270_p3 <= 
        ap_const_lv10_0 when (tmp_33_12_fu_2256_p2(0) = '1') else 
        ap_port_reg_calo_13_hwPhi_V_rea;
    calo_14_hwEta_V_rea_2_fu_2374_p3 <= 
        ap_const_lv10_0 when (tmp_33_13_fu_2368_p2(0) = '1') else 
        ap_port_reg_calo_14_hwEta_V_rea;
    calo_14_hwPhi_V_rea_2_fu_2382_p3 <= 
        ap_const_lv10_0 when (tmp_33_13_fu_2368_p2(0) = '1') else 
        ap_port_reg_calo_14_hwPhi_V_rea;
    calo_1_hwEta_V_read_2_fu_1411_p3 <= 
        ap_const_lv10_0 when (tmp_33_1_fu_1406_p2(0) = '1') else 
        ap_port_reg_calo_1_hwEta_V_read;
    calo_1_hwPhi_V_read_2_fu_1419_p3 <= 
        ap_const_lv10_0 when (tmp_33_1_fu_1406_p2(0) = '1') else 
        ap_port_reg_calo_1_hwPhi_V_read;
    calo_2_hwEta_V_read_2_fu_1441_p3 <= 
        ap_const_lv10_0 when (tmp_33_2_fu_1436_p2(0) = '1') else 
        ap_port_reg_calo_2_hwEta_V_read;
    calo_2_hwPhi_V_read_2_fu_1449_p3 <= 
        ap_const_lv10_0 when (tmp_33_2_fu_1436_p2(0) = '1') else 
        ap_port_reg_calo_2_hwPhi_V_read;
    calo_3_hwEta_V_read_2_fu_1471_p3 <= 
        ap_const_lv10_0 when (tmp_33_3_fu_1466_p2(0) = '1') else 
        ap_port_reg_calo_3_hwEta_V_read;
    calo_3_hwPhi_V_read_2_fu_1479_p3 <= 
        ap_const_lv10_0 when (tmp_33_3_fu_1466_p2(0) = '1') else 
        ap_port_reg_calo_3_hwPhi_V_read;
    calo_4_hwEta_V_read_2_fu_1501_p3 <= 
        ap_const_lv10_0 when (tmp_33_4_fu_1496_p2(0) = '1') else 
        ap_port_reg_calo_4_hwEta_V_read;
    calo_4_hwPhi_V_read_2_fu_1509_p3 <= 
        ap_const_lv10_0 when (tmp_33_4_fu_1496_p2(0) = '1') else 
        ap_port_reg_calo_4_hwPhi_V_read;
    calo_5_hwEta_V_read_2_fu_1531_p3 <= 
        ap_const_lv10_0 when (tmp_33_5_fu_1526_p2(0) = '1') else 
        ap_port_reg_calo_5_hwEta_V_read;
    calo_5_hwPhi_V_read_2_fu_1539_p3 <= 
        ap_const_lv10_0 when (tmp_33_5_fu_1526_p2(0) = '1') else 
        ap_port_reg_calo_5_hwPhi_V_read;
    calo_6_hwEta_V_read_2_fu_1561_p3 <= 
        ap_const_lv10_0 when (tmp_33_6_fu_1556_p2(0) = '1') else 
        ap_port_reg_calo_6_hwEta_V_read;
    calo_6_hwPhi_V_read_2_fu_1569_p3 <= 
        ap_const_lv10_0 when (tmp_33_6_fu_1556_p2(0) = '1') else 
        ap_port_reg_calo_6_hwPhi_V_read;
    calo_7_hwEta_V_read_2_fu_1591_p3 <= 
        ap_const_lv10_0 when (tmp_33_7_fu_1586_p2(0) = '1') else 
        ap_port_reg_calo_7_hwEta_V_read;
    calo_7_hwPhi_V_read_2_fu_1599_p3 <= 
        ap_const_lv10_0 when (tmp_33_7_fu_1586_p2(0) = '1') else 
        ap_port_reg_calo_7_hwPhi_V_read;
    calo_8_hwEta_V_read_2_fu_1702_p3 <= 
        ap_const_lv10_0 when (tmp_33_8_fu_1696_p2(0) = '1') else 
        ap_port_reg_calo_8_hwEta_V_read;
    calo_8_hwPhi_V_read_2_fu_1710_p3 <= 
        ap_const_lv10_0 when (tmp_33_8_fu_1696_p2(0) = '1') else 
        ap_port_reg_calo_8_hwPhi_V_read;
    calo_9_hwEta_V_read_2_fu_1814_p3 <= 
        ap_const_lv10_0 when (tmp_33_9_fu_1808_p2(0) = '1') else 
        ap_port_reg_calo_9_hwEta_V_read;
    calo_9_hwPhi_V_read_2_fu_1822_p3 <= 
        ap_const_lv10_0 when (tmp_33_9_fu_1808_p2(0) = '1') else 
        ap_port_reg_calo_9_hwPhi_V_read;
    calopt_V_2_10_fu_1952_p2 <= std_logic_vector(unsigned(ap_port_reg_calo_11_hwPt_V_read) - unsigned(sumtk_11_V_read_2_reg_2872));
    calopt_V_2_11_fu_2064_p2 <= std_logic_vector(unsigned(ap_port_reg_calo_12_hwPt_V_read) - unsigned(sumtk_12_V_read_2_reg_2867));
    calopt_V_2_12_fu_2176_p2 <= std_logic_vector(unsigned(ap_port_reg_calo_13_hwPt_V_read) - unsigned(sumtk_13_V_read_2_reg_2862));
    calopt_V_2_13_fu_2288_p2 <= std_logic_vector(unsigned(ap_port_reg_calo_14_hwPt_V_read) - unsigned(sumtk_14_V_read_2_reg_2857));
    calopt_V_2_1_fu_717_p2 <= std_logic_vector(unsigned(calo_1_hwPt_V_read) - unsigned(sumtk_1_V_read));
    calopt_V_2_2_fu_806_p2 <= std_logic_vector(unsigned(calo_2_hwPt_V_read) - unsigned(sumtk_2_V_read));
    calopt_V_2_3_fu_895_p2 <= std_logic_vector(unsigned(calo_3_hwPt_V_read) - unsigned(sumtk_3_V_read));
    calopt_V_2_4_fu_984_p2 <= std_logic_vector(unsigned(calo_4_hwPt_V_read) - unsigned(sumtk_4_V_read));
    calopt_V_2_5_fu_1073_p2 <= std_logic_vector(unsigned(calo_5_hwPt_V_read) - unsigned(sumtk_5_V_read));
    calopt_V_2_6_fu_1162_p2 <= std_logic_vector(unsigned(calo_6_hwPt_V_read) - unsigned(sumtk_6_V_read));
    calopt_V_2_7_fu_1251_p2 <= std_logic_vector(unsigned(calo_7_hwPt_V_read) - unsigned(sumtk_7_V_read));
    calopt_V_2_8_fu_1616_p2 <= std_logic_vector(unsigned(ap_port_reg_calo_8_hwPt_V_read) - unsigned(sumtk_8_V_read_2_reg_2887));
    calopt_V_2_9_fu_1728_p2 <= std_logic_vector(unsigned(ap_port_reg_calo_9_hwPt_V_read) - unsigned(sumtk_9_V_read_2_reg_2882));
    calopt_V_2_fu_628_p2 <= std_logic_vector(unsigned(calo_0_hwPt_V_read) - unsigned(sumtk_0_V_read));
    calopt_V_2_s_fu_1840_p2 <= std_logic_vector(unsigned(ap_port_reg_calo_10_hwPt_V_read) - unsigned(sumtk_10_V_read_2_reg_2877));
    lhs_V_10_fu_1855_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_s_fu_1840_p2),32));
    lhs_V_11_fu_1967_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_10_fu_1952_p2),32));
    lhs_V_12_fu_2079_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_11_fu_2064_p2),32));
    lhs_V_13_fu_2191_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_12_fu_2176_p2),32));
    lhs_V_14_fu_2303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_13_fu_2288_p2),32));
    lhs_V_1_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_1_fu_717_p2),32));
    lhs_V_2_fu_822_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_2_fu_806_p2),32));
    lhs_V_3_fu_911_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_3_fu_895_p2),32));
    lhs_V_4_fu_1000_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_4_fu_984_p2),32));
    lhs_V_5_fu_1089_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_5_fu_1073_p2),32));
    lhs_V_6_fu_1178_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_6_fu_1162_p2),32));
    lhs_V_7_fu_1267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_7_fu_1251_p2),32));
    lhs_V_8_fu_1631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_8_fu_1616_p2),32));
    lhs_V_9_fu_1743_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_9_fu_1728_p2),32));
    lhs_V_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(calopt_V_2_fu_628_p2),32));
    op2_assign_10_fu_1985_p2 <= std_logic_vector(unsigned(ap_port_reg_sumtkerr2_11_read) + unsigned(tmp_31_10_fu_1981_p1));
    op2_assign_11_fu_2097_p2 <= std_logic_vector(unsigned(ap_port_reg_sumtkerr2_12_read) + unsigned(tmp_31_11_fu_2093_p1));
    op2_assign_12_fu_2209_p2 <= std_logic_vector(unsigned(ap_port_reg_sumtkerr2_13_read) + unsigned(tmp_31_12_fu_2205_p1));
    op2_assign_13_fu_2321_p2 <= std_logic_vector(unsigned(ap_port_reg_sumtkerr2_14_read) + unsigned(tmp_31_13_fu_2317_p1));
    op2_assign_1_fu_751_p2 <= std_logic_vector(unsigned(sumtkerr2_1_read) + unsigned(tmp_31_1_fu_747_p1));
    op2_assign_2_fu_840_p2 <= std_logic_vector(unsigned(sumtkerr2_2_read) + unsigned(tmp_31_2_fu_836_p1));
    op2_assign_3_fu_929_p2 <= std_logic_vector(unsigned(sumtkerr2_3_read) + unsigned(tmp_31_3_fu_925_p1));
    op2_assign_4_fu_1018_p2 <= std_logic_vector(unsigned(sumtkerr2_4_read) + unsigned(tmp_31_4_fu_1014_p1));
    op2_assign_5_fu_1107_p2 <= std_logic_vector(unsigned(sumtkerr2_5_read) + unsigned(tmp_31_5_fu_1103_p1));
    op2_assign_6_fu_1196_p2 <= std_logic_vector(unsigned(sumtkerr2_6_read) + unsigned(tmp_31_6_fu_1192_p1));
    op2_assign_7_fu_1285_p2 <= std_logic_vector(unsigned(sumtkerr2_7_read) + unsigned(tmp_31_7_fu_1281_p1));
    op2_assign_8_fu_1649_p2 <= std_logic_vector(unsigned(ap_port_reg_sumtkerr2_8_read) + unsigned(tmp_31_8_fu_1645_p1));
    op2_assign_9_fu_1761_p2 <= std_logic_vector(unsigned(ap_port_reg_sumtkerr2_9_read) + unsigned(tmp_31_9_fu_1757_p1));
    op2_assign_fu_662_p2 <= std_logic_vector(unsigned(sumtkerr2_0_read) + unsigned(tmp_23_fu_658_p1));
    op2_assign_s_fu_1873_p2 <= std_logic_vector(unsigned(ap_port_reg_sumtkerr2_10_read) + unsigned(tmp_31_s_fu_1869_p1));
    pfout_0_hwId_V_writ_fu_1402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_fu_1397_p2),3));
    pfout_0_hwPt_V_writ_fu_703_p3 <= 
        calo_0_hwPt_V_read when (tmp_s_fu_622_p2(0) = '1') else 
        sel_tmp3_cast_fu_699_p1;
    pfout_10_hwId_V_wri_fu_1948_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_s_fu_1942_p2),3));
    pfout_10_hwPt_V_wri_fu_1913_p3 <= 
        ap_port_reg_calo_10_hwPt_V_read when (tmp_10_reg_2960(0) = '1') else 
        sel_tmp53_cast_fu_1909_p1;
    pfout_11_hwId_V_wri_fu_2060_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_10_fu_2054_p2),3));
    pfout_11_hwPt_V_wri_fu_2025_p3 <= 
        ap_port_reg_calo_11_hwPt_V_read when (tmp_11_reg_2966(0) = '1') else 
        sel_tmp58_cast_fu_2021_p1;
    pfout_12_hwId_V_wri_fu_2172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_11_fu_2166_p2),3));
    pfout_12_hwPt_V_wri_fu_2137_p3 <= 
        ap_port_reg_calo_12_hwPt_V_read when (tmp_12_reg_2972(0) = '1') else 
        sel_tmp63_cast_fu_2133_p1;
    pfout_13_hwId_V_wri_fu_2284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_12_fu_2278_p2),3));
    pfout_13_hwPt_V_wri_fu_2249_p3 <= 
        ap_port_reg_calo_13_hwPt_V_read when (tmp_13_reg_2978(0) = '1') else 
        sel_tmp68_cast_fu_2245_p1;
    pfout_14_hwId_V_wri_fu_2396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_13_fu_2390_p2),3));
    pfout_14_hwPt_V_wri_fu_2361_p3 <= 
        ap_port_reg_calo_14_hwPt_V_read when (tmp_s_53_reg_2984(0) = '1') else 
        sel_tmp73_cast_fu_2357_p1;
    pfout_1_hwId_V_writ_fu_1432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_1_fu_1427_p2),3));
    pfout_1_hwPt_V_writ_fu_792_p3 <= 
        calo_1_hwPt_V_read when (tmp_1_fu_711_p2(0) = '1') else 
        sel_tmp8_cast_fu_788_p1;
    pfout_2_hwId_V_writ_fu_1462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_2_fu_1457_p2),3));
    pfout_2_hwPt_V_writ_fu_881_p3 <= 
        calo_2_hwPt_V_read when (tmp_2_fu_800_p2(0) = '1') else 
        sel_tmp13_cast_fu_877_p1;
    pfout_3_hwId_V_writ_fu_1492_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_3_fu_1487_p2),3));
    pfout_3_hwPt_V_writ_fu_970_p3 <= 
        calo_3_hwPt_V_read when (tmp_3_fu_889_p2(0) = '1') else 
        sel_tmp18_cast_fu_966_p1;
    pfout_4_hwId_V_writ_fu_1522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_4_fu_1517_p2),3));
    pfout_4_hwPt_V_writ_fu_1059_p3 <= 
        calo_4_hwPt_V_read when (tmp_4_fu_978_p2(0) = '1') else 
        sel_tmp23_cast_fu_1055_p1;
    pfout_5_hwId_V_writ_fu_1552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_5_fu_1547_p2),3));
    pfout_5_hwPt_V_writ_fu_1148_p3 <= 
        calo_5_hwPt_V_read when (tmp_5_fu_1067_p2(0) = '1') else 
        sel_tmp28_cast_fu_1144_p1;
    pfout_6_hwId_V_writ_fu_1582_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_6_fu_1577_p2),3));
    pfout_6_hwPt_V_writ_fu_1237_p3 <= 
        calo_6_hwPt_V_read when (tmp_6_fu_1156_p2(0) = '1') else 
        sel_tmp33_cast_fu_1233_p1;
    pfout_7_hwId_V_writ_fu_1612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_7_fu_1607_p2),3));
    pfout_7_hwPt_V_writ_fu_1326_p3 <= 
        calo_7_hwPt_V_read when (tmp_7_fu_1245_p2(0) = '1') else 
        sel_tmp38_cast_fu_1322_p1;
    pfout_8_hwId_V_writ_fu_1724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_8_fu_1718_p2),3));
    pfout_8_hwPt_V_writ_fu_1689_p3 <= 
        ap_port_reg_calo_8_hwPt_V_read when (tmp_8_reg_2948(0) = '1') else 
        sel_tmp43_cast_fu_1685_p1;
    pfout_9_hwId_V_writ_fu_1836_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_9_fu_1830_p2),3));
    pfout_9_hwPt_V_writ_fu_1801_p3 <= 
        ap_port_reg_calo_9_hwPt_V_read when (tmp_9_reg_2954(0) = '1') else 
        sel_tmp48_cast_fu_1797_p1;
    r_V_10_fu_2822_p0 <= lhs_V_10_fu_1855_p1(16 - 1 downto 0);
    r_V_10_fu_2822_p1 <= lhs_V_10_fu_1855_p1(16 - 1 downto 0);
    r_V_11_fu_2829_p0 <= lhs_V_11_fu_1967_p1(16 - 1 downto 0);
    r_V_11_fu_2829_p1 <= lhs_V_11_fu_1967_p1(16 - 1 downto 0);
    r_V_12_fu_2836_p0 <= lhs_V_12_fu_2079_p1(16 - 1 downto 0);
    r_V_12_fu_2836_p1 <= lhs_V_12_fu_2079_p1(16 - 1 downto 0);
    r_V_13_fu_2843_p0 <= lhs_V_13_fu_2191_p1(16 - 1 downto 0);
    r_V_13_fu_2843_p1 <= lhs_V_13_fu_2191_p1(16 - 1 downto 0);
    r_V_14_fu_2850_p0 <= lhs_V_14_fu_2303_p1(16 - 1 downto 0);
    r_V_14_fu_2850_p1 <= lhs_V_14_fu_2303_p1(16 - 1 downto 0);
    r_V_1_fu_2759_p0 <= lhs_V_1_fu_733_p1(16 - 1 downto 0);
    r_V_1_fu_2759_p1 <= lhs_V_1_fu_733_p1(16 - 1 downto 0);
    r_V_2_fu_2766_p0 <= lhs_V_2_fu_822_p1(16 - 1 downto 0);
    r_V_2_fu_2766_p1 <= lhs_V_2_fu_822_p1(16 - 1 downto 0);
    r_V_3_fu_2773_p0 <= lhs_V_3_fu_911_p1(16 - 1 downto 0);
    r_V_3_fu_2773_p1 <= lhs_V_3_fu_911_p1(16 - 1 downto 0);
    r_V_4_fu_2780_p0 <= lhs_V_4_fu_1000_p1(16 - 1 downto 0);
    r_V_4_fu_2780_p1 <= lhs_V_4_fu_1000_p1(16 - 1 downto 0);
    r_V_5_fu_2787_p0 <= lhs_V_5_fu_1089_p1(16 - 1 downto 0);
    r_V_5_fu_2787_p1 <= lhs_V_5_fu_1089_p1(16 - 1 downto 0);
    r_V_6_fu_2794_p0 <= lhs_V_6_fu_1178_p1(16 - 1 downto 0);
    r_V_6_fu_2794_p1 <= lhs_V_6_fu_1178_p1(16 - 1 downto 0);
    r_V_7_fu_2801_p0 <= lhs_V_7_fu_1267_p1(16 - 1 downto 0);
    r_V_7_fu_2801_p1 <= lhs_V_7_fu_1267_p1(16 - 1 downto 0);
    r_V_8_fu_2808_p0 <= lhs_V_8_fu_1631_p1(16 - 1 downto 0);
    r_V_8_fu_2808_p1 <= lhs_V_8_fu_1631_p1(16 - 1 downto 0);
    r_V_9_fu_2815_p0 <= lhs_V_9_fu_1743_p1(16 - 1 downto 0);
    r_V_9_fu_2815_p1 <= lhs_V_9_fu_1743_p1(16 - 1 downto 0);
    r_V_fu_2752_p0 <= lhs_V_fu_644_p1(16 - 1 downto 0);
    r_V_fu_2752_p1 <= lhs_V_fu_644_p1(16 - 1 downto 0);
    sel_tmp10_fu_851_p2 <= (tmp_2_fu_800_p2 xor ap_const_lv1_1);
    sel_tmp12_fu_863_p2 <= (tmp_30_2_fu_816_p2 and tmp77_fu_857_p2);
    sel_tmp13_cast_fu_877_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp13_fu_869_p3),16));
    sel_tmp13_fu_869_p3 <= 
        tmp_778_fu_812_p1 when (sel_tmp12_fu_863_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp15_fu_940_p2 <= (tmp_3_fu_889_p2 xor ap_const_lv1_1);
    sel_tmp17_fu_952_p2 <= (tmp_30_3_fu_905_p2 and tmp78_fu_946_p2);
    sel_tmp18_cast_fu_966_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp18_fu_958_p3),16));
    sel_tmp18_fu_958_p3 <= 
        tmp_779_fu_901_p1 when (sel_tmp17_fu_952_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp20_fu_1029_p2 <= (tmp_4_fu_978_p2 xor ap_const_lv1_1);
    sel_tmp22_fu_1041_p2 <= (tmp_30_4_fu_994_p2 and tmp79_fu_1035_p2);
    sel_tmp23_cast_fu_1055_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp23_fu_1047_p3),16));
    sel_tmp23_fu_1047_p3 <= 
        tmp_780_fu_990_p1 when (sel_tmp22_fu_1041_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp25_fu_1118_p2 <= (tmp_5_fu_1067_p2 xor ap_const_lv1_1);
    sel_tmp27_fu_1130_p2 <= (tmp_30_5_fu_1083_p2 and tmp80_fu_1124_p2);
    sel_tmp28_cast_fu_1144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp28_fu_1136_p3),16));
    sel_tmp28_fu_1136_p3 <= 
        tmp_781_fu_1079_p1 when (sel_tmp27_fu_1130_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp2_fu_685_p2 <= (tmp_21_fu_638_p2 and tmp75_fu_679_p2);
    sel_tmp30_fu_1207_p2 <= (tmp_6_fu_1156_p2 xor ap_const_lv1_1);
    sel_tmp32_fu_1219_p2 <= (tmp_30_6_fu_1172_p2 and tmp81_fu_1213_p2);
    sel_tmp33_cast_fu_1233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp33_fu_1225_p3),16));
    sel_tmp33_fu_1225_p3 <= 
        tmp_782_fu_1168_p1 when (sel_tmp32_fu_1219_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp35_fu_1296_p2 <= (tmp_7_fu_1245_p2 xor ap_const_lv1_1);
    sel_tmp37_fu_1308_p2 <= (tmp_30_7_fu_1261_p2 and tmp82_fu_1302_p2);
    sel_tmp38_cast_fu_1322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp38_fu_1314_p3),16));
    sel_tmp38_fu_1314_p3 <= 
        tmp_783_fu_1257_p1 when (sel_tmp37_fu_1308_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp3_cast_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp3_fu_691_p3),16));
    sel_tmp3_fu_691_p3 <= 
        tmp_fu_634_p1 when (sel_tmp2_fu_685_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp40_fu_1660_p2 <= (tmp_8_reg_2948 xor ap_const_lv1_1);
    sel_tmp42_fu_1671_p2 <= (tmp_30_8_fu_1625_p2 and tmp83_fu_1665_p2);
    sel_tmp43_cast_fu_1685_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp43_fu_1677_p3),16));
    sel_tmp43_fu_1677_p3 <= 
        tmp_784_fu_1621_p1 when (sel_tmp42_fu_1671_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp45_fu_1772_p2 <= (tmp_9_reg_2954 xor ap_const_lv1_1);
    sel_tmp47_fu_1783_p2 <= (tmp_30_9_fu_1737_p2 and tmp84_fu_1777_p2);
    sel_tmp48_cast_fu_1797_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp48_fu_1789_p3),16));
    sel_tmp48_fu_1789_p3 <= 
        tmp_785_fu_1733_p1 when (sel_tmp47_fu_1783_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp50_fu_1884_p2 <= (tmp_10_reg_2960 xor ap_const_lv1_1);
    sel_tmp52_fu_1895_p2 <= (tmp_30_s_fu_1849_p2 and tmp85_fu_1889_p2);
    sel_tmp53_cast_fu_1909_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp53_fu_1901_p3),16));
    sel_tmp53_fu_1901_p3 <= 
        tmp_786_fu_1845_p1 when (sel_tmp52_fu_1895_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp55_fu_1996_p2 <= (tmp_11_reg_2966 xor ap_const_lv1_1);
    sel_tmp57_fu_2007_p2 <= (tmp_30_10_fu_1961_p2 and tmp86_fu_2001_p2);
    sel_tmp58_cast_fu_2021_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp58_fu_2013_p3),16));
    sel_tmp58_fu_2013_p3 <= 
        tmp_787_fu_1957_p1 when (sel_tmp57_fu_2007_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp5_fu_762_p2 <= (tmp_1_fu_711_p2 xor ap_const_lv1_1);
    sel_tmp60_fu_2108_p2 <= (tmp_12_reg_2972 xor ap_const_lv1_1);
    sel_tmp62_fu_2119_p2 <= (tmp_30_11_fu_2073_p2 and tmp87_fu_2113_p2);
    sel_tmp63_cast_fu_2133_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp63_fu_2125_p3),16));
    sel_tmp63_fu_2125_p3 <= 
        tmp_788_fu_2069_p1 when (sel_tmp62_fu_2119_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp65_fu_2220_p2 <= (tmp_13_reg_2978 xor ap_const_lv1_1);
    sel_tmp67_fu_2231_p2 <= (tmp_30_12_fu_2185_p2 and tmp88_fu_2225_p2);
    sel_tmp68_cast_fu_2245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp68_fu_2237_p3),16));
    sel_tmp68_fu_2237_p3 <= 
        tmp_789_fu_2181_p1 when (sel_tmp67_fu_2231_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp70_fu_2332_p2 <= (tmp_s_53_reg_2984 xor ap_const_lv1_1);
    sel_tmp72_fu_2343_p2 <= (tmp_30_13_fu_2297_p2 and tmp89_fu_2337_p2);
    sel_tmp73_cast_fu_2357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp73_fu_2349_p3),16));
    sel_tmp73_fu_2349_p3 <= 
        tmp_790_fu_2293_p1 when (sel_tmp72_fu_2343_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp7_fu_774_p2 <= (tmp_30_1_fu_727_p2 and tmp76_fu_768_p2);
    sel_tmp8_cast_fu_788_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp8_fu_780_p3),16));
    sel_tmp8_fu_780_p3 <= 
        tmp_777_fu_723_p1 when (sel_tmp7_fu_774_p2(0) = '1') else 
        ap_const_lv15_0;
    sel_tmp_fu_673_p2 <= (tmp_s_fu_622_p2 xor ap_const_lv1_1);
    tmp75_fu_679_p2 <= (tmp_24_fu_668_p2 and sel_tmp_fu_673_p2);
    tmp76_fu_768_p2 <= (tmp_32_1_fu_757_p2 and sel_tmp5_fu_762_p2);
    tmp77_fu_857_p2 <= (tmp_32_2_fu_846_p2 and sel_tmp10_fu_851_p2);
    tmp78_fu_946_p2 <= (tmp_32_3_fu_935_p2 and sel_tmp15_fu_940_p2);
    tmp79_fu_1035_p2 <= (tmp_32_4_fu_1024_p2 and sel_tmp20_fu_1029_p2);
    tmp80_fu_1124_p2 <= (tmp_32_5_fu_1113_p2 and sel_tmp25_fu_1118_p2);
    tmp81_fu_1213_p2 <= (tmp_32_6_fu_1202_p2 and sel_tmp30_fu_1207_p2);
    tmp82_fu_1302_p2 <= (tmp_32_7_fu_1291_p2 and sel_tmp35_fu_1296_p2);
    tmp83_fu_1665_p2 <= (tmp_32_8_fu_1655_p2 and sel_tmp40_fu_1660_p2);
    tmp84_fu_1777_p2 <= (tmp_32_9_fu_1767_p2 and sel_tmp45_fu_1772_p2);
    tmp85_fu_1889_p2 <= (tmp_32_s_fu_1879_p2 and sel_tmp50_fu_1884_p2);
    tmp86_fu_2001_p2 <= (tmp_32_10_fu_1991_p2 and sel_tmp55_fu_1996_p2);
    tmp87_fu_2113_p2 <= (tmp_32_11_fu_2103_p2 and sel_tmp60_fu_2108_p2);
    tmp88_fu_2225_p2 <= (tmp_32_12_fu_2215_p2 and sel_tmp65_fu_2220_p2);
    tmp89_fu_2337_p2 <= (tmp_32_13_fu_2327_p2 and sel_tmp70_fu_2332_p2);
    tmp_10_fu_1346_p2 <= "1" when (sumtk_10_V_read = ap_const_lv16_0) else "0";
    tmp_11_fu_1352_p2 <= "1" when (sumtk_11_V_read = ap_const_lv16_0) else "0";
    tmp_12_fu_1358_p2 <= "1" when (sumtk_12_V_read = ap_const_lv16_0) else "0";
    tmp_13_fu_1364_p2 <= "1" when (sumtk_13_V_read = ap_const_lv16_0) else "0";
    tmp_1_fu_711_p2 <= "1" when (sumtk_1_V_read = ap_const_lv16_0) else "0";
    tmp_21_fu_638_p2 <= "1" when (signed(calopt_V_2_fu_628_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_22_fu_648_p4 <= sumtkerr2_0_read(31 downto 1);
        tmp_23_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_22_fu_648_p4),32));

    tmp_24_fu_668_p2 <= "1" when (signed(r_V_fu_2752_p2) > signed(op2_assign_fu_662_p2)) else "0";
    tmp_25_fu_1376_p2 <= "1" when (pfout_0_hwPt_V_writ_reg_2892 = ap_const_lv16_0) else "0";
    tmp_26_fu_1397_p2 <= "0" when (pfout_0_hwPt_V_writ_reg_2892 = ap_const_lv16_0) else "1";
    tmp_27_fu_737_p4 <= sumtkerr2_1_read(31 downto 1);
    tmp_28_fu_826_p4 <= sumtkerr2_2_read(31 downto 1);
    tmp_29_fu_915_p4 <= sumtkerr2_3_read(31 downto 1);
    tmp_2_fu_800_p2 <= "1" when (sumtk_2_V_read = ap_const_lv16_0) else "0";
    tmp_30_10_fu_1961_p2 <= "1" when (signed(calopt_V_2_10_fu_1952_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_11_fu_2073_p2 <= "1" when (signed(calopt_V_2_11_fu_2064_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_12_fu_2185_p2 <= "1" when (signed(calopt_V_2_12_fu_2176_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_13_fu_2297_p2 <= "1" when (signed(calopt_V_2_13_fu_2288_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_1_fu_727_p2 <= "1" when (signed(calopt_V_2_1_fu_717_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_2_fu_816_p2 <= "1" when (signed(calopt_V_2_2_fu_806_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_3_fu_905_p2 <= "1" when (signed(calopt_V_2_3_fu_895_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_4_fu_994_p2 <= "1" when (signed(calopt_V_2_4_fu_984_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_5_fu_1083_p2 <= "1" when (signed(calopt_V_2_5_fu_1073_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_6_fu_1172_p2 <= "1" when (signed(calopt_V_2_6_fu_1162_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_7_fu_1261_p2 <= "1" when (signed(calopt_V_2_7_fu_1251_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_8_fu_1625_p2 <= "1" when (signed(calopt_V_2_8_fu_1616_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_9_fu_1737_p2 <= "1" when (signed(calopt_V_2_9_fu_1728_p2) > signed(ap_const_lv16_0)) else "0";
    tmp_30_fu_1004_p4 <= sumtkerr2_4_read(31 downto 1);
    tmp_30_s_fu_1849_p2 <= "1" when (signed(calopt_V_2_s_fu_1840_p2) > signed(ap_const_lv16_0)) else "0";
        tmp_31_10_fu_1981_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_37_fu_1971_p4),32));

        tmp_31_11_fu_2093_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_38_fu_2083_p4),32));

        tmp_31_12_fu_2205_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_39_fu_2195_p4),32));

        tmp_31_13_fu_2317_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_40_fu_2307_p4),32));

        tmp_31_1_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_27_fu_737_p4),32));

        tmp_31_2_fu_836_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_28_fu_826_p4),32));

        tmp_31_3_fu_925_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_29_fu_915_p4),32));

        tmp_31_4_fu_1014_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_30_fu_1004_p4),32));

        tmp_31_5_fu_1103_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_31_fu_1093_p4),32));

        tmp_31_6_fu_1192_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_32_fu_1182_p4),32));

        tmp_31_7_fu_1281_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_33_fu_1271_p4),32));

        tmp_31_8_fu_1645_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_34_fu_1635_p4),32));

        tmp_31_9_fu_1757_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_35_fu_1747_p4),32));

    tmp_31_fu_1093_p4 <= sumtkerr2_5_read(31 downto 1);
        tmp_31_s_fu_1869_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_36_fu_1859_p4),32));

    tmp_32_10_fu_1991_p2 <= "1" when (signed(r_V_11_fu_2829_p2) > signed(op2_assign_10_fu_1985_p2)) else "0";
    tmp_32_11_fu_2103_p2 <= "1" when (signed(r_V_12_fu_2836_p2) > signed(op2_assign_11_fu_2097_p2)) else "0";
    tmp_32_12_fu_2215_p2 <= "1" when (signed(r_V_13_fu_2843_p2) > signed(op2_assign_12_fu_2209_p2)) else "0";
    tmp_32_13_fu_2327_p2 <= "1" when (signed(r_V_14_fu_2850_p2) > signed(op2_assign_13_fu_2321_p2)) else "0";
    tmp_32_1_fu_757_p2 <= "1" when (signed(r_V_1_fu_2759_p2) > signed(op2_assign_1_fu_751_p2)) else "0";
    tmp_32_2_fu_846_p2 <= "1" when (signed(r_V_2_fu_2766_p2) > signed(op2_assign_2_fu_840_p2)) else "0";
    tmp_32_3_fu_935_p2 <= "1" when (signed(r_V_3_fu_2773_p2) > signed(op2_assign_3_fu_929_p2)) else "0";
    tmp_32_4_fu_1024_p2 <= "1" when (signed(r_V_4_fu_2780_p2) > signed(op2_assign_4_fu_1018_p2)) else "0";
    tmp_32_5_fu_1113_p2 <= "1" when (signed(r_V_5_fu_2787_p2) > signed(op2_assign_5_fu_1107_p2)) else "0";
    tmp_32_6_fu_1202_p2 <= "1" when (signed(r_V_6_fu_2794_p2) > signed(op2_assign_6_fu_1196_p2)) else "0";
    tmp_32_7_fu_1291_p2 <= "1" when (signed(r_V_7_fu_2801_p2) > signed(op2_assign_7_fu_1285_p2)) else "0";
    tmp_32_8_fu_1655_p2 <= "1" when (signed(r_V_8_fu_2808_p2) > signed(op2_assign_8_fu_1649_p2)) else "0";
    tmp_32_9_fu_1767_p2 <= "1" when (signed(r_V_9_fu_2815_p2) > signed(op2_assign_9_fu_1761_p2)) else "0";
    tmp_32_fu_1182_p4 <= sumtkerr2_6_read(31 downto 1);
    tmp_32_s_fu_1879_p2 <= "1" when (signed(r_V_10_fu_2822_p2) > signed(op2_assign_s_fu_1873_p2)) else "0";
    tmp_33_10_fu_2032_p2 <= "1" when (pfout_11_hwPt_V_wri_fu_2025_p3 = ap_const_lv16_0) else "0";
    tmp_33_11_fu_2144_p2 <= "1" when (pfout_12_hwPt_V_wri_fu_2137_p3 = ap_const_lv16_0) else "0";
    tmp_33_12_fu_2256_p2 <= "1" when (pfout_13_hwPt_V_wri_fu_2249_p3 = ap_const_lv16_0) else "0";
    tmp_33_13_fu_2368_p2 <= "1" when (pfout_14_hwPt_V_wri_fu_2361_p3 = ap_const_lv16_0) else "0";
    tmp_33_1_fu_1406_p2 <= "1" when (pfout_1_hwPt_V_writ_reg_2899 = ap_const_lv16_0) else "0";
    tmp_33_2_fu_1436_p2 <= "1" when (pfout_2_hwPt_V_writ_reg_2906 = ap_const_lv16_0) else "0";
    tmp_33_3_fu_1466_p2 <= "1" when (pfout_3_hwPt_V_writ_reg_2913 = ap_const_lv16_0) else "0";
    tmp_33_4_fu_1496_p2 <= "1" when (pfout_4_hwPt_V_writ_reg_2920 = ap_const_lv16_0) else "0";
    tmp_33_5_fu_1526_p2 <= "1" when (pfout_5_hwPt_V_writ_reg_2927 = ap_const_lv16_0) else "0";
    tmp_33_6_fu_1556_p2 <= "1" when (pfout_6_hwPt_V_writ_reg_2934 = ap_const_lv16_0) else "0";
    tmp_33_7_fu_1586_p2 <= "1" when (pfout_7_hwPt_V_writ_reg_2941 = ap_const_lv16_0) else "0";
    tmp_33_8_fu_1696_p2 <= "1" when (pfout_8_hwPt_V_writ_fu_1689_p3 = ap_const_lv16_0) else "0";
    tmp_33_9_fu_1808_p2 <= "1" when (pfout_9_hwPt_V_writ_fu_1801_p3 = ap_const_lv16_0) else "0";
    tmp_33_fu_1271_p4 <= sumtkerr2_7_read(31 downto 1);
    tmp_33_s_fu_1920_p2 <= "1" when (pfout_10_hwPt_V_wri_fu_1913_p3 = ap_const_lv16_0) else "0";
    tmp_34_10_fu_2054_p2 <= "0" when (pfout_11_hwPt_V_wri_fu_2025_p3 = ap_const_lv16_0) else "1";
    tmp_34_11_fu_2166_p2 <= "0" when (pfout_12_hwPt_V_wri_fu_2137_p3 = ap_const_lv16_0) else "1";
    tmp_34_12_fu_2278_p2 <= "0" when (pfout_13_hwPt_V_wri_fu_2249_p3 = ap_const_lv16_0) else "1";
    tmp_34_13_fu_2390_p2 <= "0" when (pfout_14_hwPt_V_wri_fu_2361_p3 = ap_const_lv16_0) else "1";
    tmp_34_1_fu_1427_p2 <= "0" when (pfout_1_hwPt_V_writ_reg_2899 = ap_const_lv16_0) else "1";
    tmp_34_2_fu_1457_p2 <= "0" when (pfout_2_hwPt_V_writ_reg_2906 = ap_const_lv16_0) else "1";
    tmp_34_3_fu_1487_p2 <= "0" when (pfout_3_hwPt_V_writ_reg_2913 = ap_const_lv16_0) else "1";
    tmp_34_4_fu_1517_p2 <= "0" when (pfout_4_hwPt_V_writ_reg_2920 = ap_const_lv16_0) else "1";
    tmp_34_5_fu_1547_p2 <= "0" when (pfout_5_hwPt_V_writ_reg_2927 = ap_const_lv16_0) else "1";
    tmp_34_6_fu_1577_p2 <= "0" when (pfout_6_hwPt_V_writ_reg_2934 = ap_const_lv16_0) else "1";
    tmp_34_7_fu_1607_p2 <= "0" when (pfout_7_hwPt_V_writ_reg_2941 = ap_const_lv16_0) else "1";
    tmp_34_8_fu_1718_p2 <= "0" when (pfout_8_hwPt_V_writ_fu_1689_p3 = ap_const_lv16_0) else "1";
    tmp_34_9_fu_1830_p2 <= "0" when (pfout_9_hwPt_V_writ_fu_1801_p3 = ap_const_lv16_0) else "1";
    tmp_34_fu_1635_p4 <= ap_port_reg_sumtkerr2_8_read(31 downto 1);
    tmp_34_s_fu_1942_p2 <= "0" when (pfout_10_hwPt_V_wri_fu_1913_p3 = ap_const_lv16_0) else "1";
    tmp_35_fu_1747_p4 <= ap_port_reg_sumtkerr2_9_read(31 downto 1);
    tmp_36_fu_1859_p4 <= ap_port_reg_sumtkerr2_10_read(31 downto 1);
    tmp_37_fu_1971_p4 <= ap_port_reg_sumtkerr2_11_read(31 downto 1);
    tmp_38_fu_2083_p4 <= ap_port_reg_sumtkerr2_12_read(31 downto 1);
    tmp_39_fu_2195_p4 <= ap_port_reg_sumtkerr2_13_read(31 downto 1);
    tmp_3_fu_889_p2 <= "1" when (sumtk_3_V_read = ap_const_lv16_0) else "0";
    tmp_40_fu_2307_p4 <= ap_port_reg_sumtkerr2_14_read(31 downto 1);
    tmp_4_fu_978_p2 <= "1" when (sumtk_4_V_read = ap_const_lv16_0) else "0";
    tmp_5_fu_1067_p2 <= "1" when (sumtk_5_V_read = ap_const_lv16_0) else "0";
    tmp_6_fu_1156_p2 <= "1" when (sumtk_6_V_read = ap_const_lv16_0) else "0";
    tmp_777_fu_723_p1 <= calopt_V_2_1_fu_717_p2(15 - 1 downto 0);
    tmp_778_fu_812_p1 <= calopt_V_2_2_fu_806_p2(15 - 1 downto 0);
    tmp_779_fu_901_p1 <= calopt_V_2_3_fu_895_p2(15 - 1 downto 0);
    tmp_780_fu_990_p1 <= calopt_V_2_4_fu_984_p2(15 - 1 downto 0);
    tmp_781_fu_1079_p1 <= calopt_V_2_5_fu_1073_p2(15 - 1 downto 0);
    tmp_782_fu_1168_p1 <= calopt_V_2_6_fu_1162_p2(15 - 1 downto 0);
    tmp_783_fu_1257_p1 <= calopt_V_2_7_fu_1251_p2(15 - 1 downto 0);
    tmp_784_fu_1621_p1 <= calopt_V_2_8_fu_1616_p2(15 - 1 downto 0);
    tmp_785_fu_1733_p1 <= calopt_V_2_9_fu_1728_p2(15 - 1 downto 0);
    tmp_786_fu_1845_p1 <= calopt_V_2_s_fu_1840_p2(15 - 1 downto 0);
    tmp_787_fu_1957_p1 <= calopt_V_2_10_fu_1952_p2(15 - 1 downto 0);
    tmp_788_fu_2069_p1 <= calopt_V_2_11_fu_2064_p2(15 - 1 downto 0);
    tmp_789_fu_2181_p1 <= calopt_V_2_12_fu_2176_p2(15 - 1 downto 0);
    tmp_790_fu_2293_p1 <= calopt_V_2_13_fu_2288_p2(15 - 1 downto 0);
    tmp_7_fu_1245_p2 <= "1" when (sumtk_7_V_read = ap_const_lv16_0) else "0";
    tmp_8_fu_1334_p2 <= "1" when (sumtk_8_V_read = ap_const_lv16_0) else "0";
    tmp_9_fu_1340_p2 <= "1" when (sumtk_9_V_read = ap_const_lv16_0) else "0";
    tmp_fu_634_p1 <= calopt_V_2_fu_628_p2(15 - 1 downto 0);
    tmp_s_53_fu_1370_p2 <= "1" when (sumtk_14_V_read = ap_const_lv16_0) else "0";
    tmp_s_fu_622_p2 <= "1" when (sumtk_0_V_read = ap_const_lv16_0) else "0";
end behav;
