-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tk2em_photons is
port (
    ap_ready : OUT STD_LOGIC;
    calo_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_10_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_11_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_12_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_13_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_14_hwEta_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_10_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_11_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_12_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_13_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_14_hwPhi_V_rea : IN STD_LOGIC_VECTOR (9 downto 0);
    photonPt_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_12_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    photonPt_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_45 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_46 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_47 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_48 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_49 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_50 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_51 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_52 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_53 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_54 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_55 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_56 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_57 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_58 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_59 : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of tk2em_photons is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_s_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_16_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_1_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_2_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_3_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_4_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_5_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_6_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_7_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_8_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_9_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_17_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_s_fu_756_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_10_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_806_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_11_fu_828_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_12_fu_864_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_13_fu_900_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_0_hwEta_V_read_1_fu_380_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_1_hwEta_V_read_1_fu_416_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_2_hwEta_V_read_1_fu_452_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_3_hwEta_V_read_1_fu_488_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_4_hwEta_V_read_1_fu_524_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_5_hwEta_V_read_1_fu_560_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_6_hwEta_V_read_1_fu_596_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_7_hwEta_V_read_1_fu_632_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_8_hwEta_V_read_1_fu_668_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_9_hwEta_V_read_1_fu_704_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_10_hwEta_V_rea_1_fu_740_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_11_hwEta_V_rea_1_fu_776_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_12_hwEta_V_rea_1_fu_812_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_13_hwEta_V_rea_1_fu_848_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_14_hwEta_V_rea_1_fu_884_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_0_hwPhi_V_read_1_fu_388_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_1_hwPhi_V_read_1_fu_424_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_2_hwPhi_V_read_1_fu_460_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_3_hwPhi_V_read_1_fu_496_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_4_hwPhi_V_read_1_fu_532_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_5_hwPhi_V_read_1_fu_568_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_6_hwPhi_V_read_1_fu_604_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_7_hwPhi_V_read_1_fu_640_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_8_hwPhi_V_read_1_fu_676_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_9_hwPhi_V_read_1_fu_712_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_10_hwPhi_V_rea_1_fu_748_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_11_hwPhi_V_rea_1_fu_784_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_12_hwPhi_V_rea_1_fu_820_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_13_hwPhi_V_rea_1_fu_856_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_14_hwPhi_V_rea_1_fu_892_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_0_hwId_V_writ_fu_402_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_1_hwId_V_writ_fu_438_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_2_hwId_V_writ_fu_474_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_3_hwId_V_writ_fu_510_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_4_hwId_V_writ_fu_546_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_5_hwId_V_writ_fu_582_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_6_hwId_V_writ_fu_618_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_7_hwId_V_writ_fu_654_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_8_hwId_V_writ_fu_690_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_9_hwId_V_writ_fu_726_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_10_hwId_V_wri_fu_762_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_11_hwId_V_wri_fu_798_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_12_hwId_V_wri_fu_834_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_13_hwId_V_wri_fu_870_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_14_hwId_V_wri_fu_906_p3 : STD_LOGIC_VECTOR (2 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= photonPt_0_V_read;
    ap_return_1 <= photonPt_1_V_read;
    ap_return_10 <= photonPt_10_V_read;
    ap_return_11 <= photonPt_11_V_read;
    ap_return_12 <= photonPt_12_V_read;
    ap_return_13 <= photonPt_13_V_read;
    ap_return_14 <= photonPt_14_V_read;
    ap_return_15 <= calo_0_hwEta_V_read_1_fu_380_p3;
    ap_return_16 <= calo_1_hwEta_V_read_1_fu_416_p3;
    ap_return_17 <= calo_2_hwEta_V_read_1_fu_452_p3;
    ap_return_18 <= calo_3_hwEta_V_read_1_fu_488_p3;
    ap_return_19 <= calo_4_hwEta_V_read_1_fu_524_p3;
    ap_return_2 <= photonPt_2_V_read;
    ap_return_20 <= calo_5_hwEta_V_read_1_fu_560_p3;
    ap_return_21 <= calo_6_hwEta_V_read_1_fu_596_p3;
    ap_return_22 <= calo_7_hwEta_V_read_1_fu_632_p3;
    ap_return_23 <= calo_8_hwEta_V_read_1_fu_668_p3;
    ap_return_24 <= calo_9_hwEta_V_read_1_fu_704_p3;
    ap_return_25 <= calo_10_hwEta_V_rea_1_fu_740_p3;
    ap_return_26 <= calo_11_hwEta_V_rea_1_fu_776_p3;
    ap_return_27 <= calo_12_hwEta_V_rea_1_fu_812_p3;
    ap_return_28 <= calo_13_hwEta_V_rea_1_fu_848_p3;
    ap_return_29 <= calo_14_hwEta_V_rea_1_fu_884_p3;
    ap_return_3 <= photonPt_3_V_read;
    ap_return_30 <= calo_0_hwPhi_V_read_1_fu_388_p3;
    ap_return_31 <= calo_1_hwPhi_V_read_1_fu_424_p3;
    ap_return_32 <= calo_2_hwPhi_V_read_1_fu_460_p3;
    ap_return_33 <= calo_3_hwPhi_V_read_1_fu_496_p3;
    ap_return_34 <= calo_4_hwPhi_V_read_1_fu_532_p3;
    ap_return_35 <= calo_5_hwPhi_V_read_1_fu_568_p3;
    ap_return_36 <= calo_6_hwPhi_V_read_1_fu_604_p3;
    ap_return_37 <= calo_7_hwPhi_V_read_1_fu_640_p3;
    ap_return_38 <= calo_8_hwPhi_V_read_1_fu_676_p3;
    ap_return_39 <= calo_9_hwPhi_V_read_1_fu_712_p3;
    ap_return_4 <= photonPt_4_V_read;
    ap_return_40 <= calo_10_hwPhi_V_rea_1_fu_748_p3;
    ap_return_41 <= calo_11_hwPhi_V_rea_1_fu_784_p3;
    ap_return_42 <= calo_12_hwPhi_V_rea_1_fu_820_p3;
    ap_return_43 <= calo_13_hwPhi_V_rea_1_fu_856_p3;
    ap_return_44 <= calo_14_hwPhi_V_rea_1_fu_892_p3;
    ap_return_45 <= pfout_0_hwId_V_writ_fu_402_p3;
    ap_return_46 <= pfout_1_hwId_V_writ_fu_438_p3;
    ap_return_47 <= pfout_2_hwId_V_writ_fu_474_p3;
    ap_return_48 <= pfout_3_hwId_V_writ_fu_510_p3;
    ap_return_49 <= pfout_4_hwId_V_writ_fu_546_p3;
    ap_return_5 <= photonPt_5_V_read;
    ap_return_50 <= pfout_5_hwId_V_writ_fu_582_p3;
    ap_return_51 <= pfout_6_hwId_V_writ_fu_618_p3;
    ap_return_52 <= pfout_7_hwId_V_writ_fu_654_p3;
    ap_return_53 <= pfout_8_hwId_V_writ_fu_690_p3;
    ap_return_54 <= pfout_9_hwId_V_writ_fu_726_p3;
    ap_return_55 <= pfout_10_hwId_V_wri_fu_762_p3;
    ap_return_56 <= pfout_11_hwId_V_wri_fu_798_p3;
    ap_return_57 <= pfout_12_hwId_V_wri_fu_834_p3;
    ap_return_58 <= pfout_13_hwId_V_wri_fu_870_p3;
    ap_return_59 <= pfout_14_hwId_V_wri_fu_906_p3;
    ap_return_6 <= photonPt_6_V_read;
    ap_return_7 <= photonPt_7_V_read;
    ap_return_8 <= photonPt_8_V_read;
    ap_return_9 <= photonPt_9_V_read;
    calo_0_hwEta_V_read_1_fu_380_p3 <= 
        ap_const_lv10_0 when (tmp_s_fu_374_p2(0) = '1') else 
        calo_0_hwEta_V_read;
    calo_0_hwPhi_V_read_1_fu_388_p3 <= 
        ap_const_lv10_0 when (tmp_s_fu_374_p2(0) = '1') else 
        calo_0_hwPhi_V_read;
    calo_10_hwEta_V_rea_1_fu_740_p3 <= 
        ap_const_lv10_0 when (tmp_s_17_fu_734_p2(0) = '1') else 
        calo_10_hwEta_V_rea;
    calo_10_hwPhi_V_rea_1_fu_748_p3 <= 
        ap_const_lv10_0 when (tmp_s_17_fu_734_p2(0) = '1') else 
        calo_10_hwPhi_V_rea;
    calo_11_hwEta_V_rea_1_fu_776_p3 <= 
        ap_const_lv10_0 when (tmp_10_fu_770_p2(0) = '1') else 
        calo_11_hwEta_V_rea;
    calo_11_hwPhi_V_rea_1_fu_784_p3 <= 
        ap_const_lv10_0 when (tmp_10_fu_770_p2(0) = '1') else 
        calo_11_hwPhi_V_rea;
    calo_12_hwEta_V_rea_1_fu_812_p3 <= 
        ap_const_lv10_0 when (tmp_11_fu_806_p2(0) = '1') else 
        calo_12_hwEta_V_rea;
    calo_12_hwPhi_V_rea_1_fu_820_p3 <= 
        ap_const_lv10_0 when (tmp_11_fu_806_p2(0) = '1') else 
        calo_12_hwPhi_V_rea;
    calo_13_hwEta_V_rea_1_fu_848_p3 <= 
        ap_const_lv10_0 when (tmp_12_fu_842_p2(0) = '1') else 
        calo_13_hwEta_V_rea;
    calo_13_hwPhi_V_rea_1_fu_856_p3 <= 
        ap_const_lv10_0 when (tmp_12_fu_842_p2(0) = '1') else 
        calo_13_hwPhi_V_rea;
    calo_14_hwEta_V_rea_1_fu_884_p3 <= 
        ap_const_lv10_0 when (tmp_13_fu_878_p2(0) = '1') else 
        calo_14_hwEta_V_rea;
    calo_14_hwPhi_V_rea_1_fu_892_p3 <= 
        ap_const_lv10_0 when (tmp_13_fu_878_p2(0) = '1') else 
        calo_14_hwPhi_V_rea;
    calo_1_hwEta_V_read_1_fu_416_p3 <= 
        ap_const_lv10_0 when (tmp_1_16_fu_410_p2(0) = '1') else 
        calo_1_hwEta_V_read;
    calo_1_hwPhi_V_read_1_fu_424_p3 <= 
        ap_const_lv10_0 when (tmp_1_16_fu_410_p2(0) = '1') else 
        calo_1_hwPhi_V_read;
    calo_2_hwEta_V_read_1_fu_452_p3 <= 
        ap_const_lv10_0 when (tmp_2_fu_446_p2(0) = '1') else 
        calo_2_hwEta_V_read;
    calo_2_hwPhi_V_read_1_fu_460_p3 <= 
        ap_const_lv10_0 when (tmp_2_fu_446_p2(0) = '1') else 
        calo_2_hwPhi_V_read;
    calo_3_hwEta_V_read_1_fu_488_p3 <= 
        ap_const_lv10_0 when (tmp_3_fu_482_p2(0) = '1') else 
        calo_3_hwEta_V_read;
    calo_3_hwPhi_V_read_1_fu_496_p3 <= 
        ap_const_lv10_0 when (tmp_3_fu_482_p2(0) = '1') else 
        calo_3_hwPhi_V_read;
    calo_4_hwEta_V_read_1_fu_524_p3 <= 
        ap_const_lv10_0 when (tmp_4_fu_518_p2(0) = '1') else 
        calo_4_hwEta_V_read;
    calo_4_hwPhi_V_read_1_fu_532_p3 <= 
        ap_const_lv10_0 when (tmp_4_fu_518_p2(0) = '1') else 
        calo_4_hwPhi_V_read;
    calo_5_hwEta_V_read_1_fu_560_p3 <= 
        ap_const_lv10_0 when (tmp_5_fu_554_p2(0) = '1') else 
        calo_5_hwEta_V_read;
    calo_5_hwPhi_V_read_1_fu_568_p3 <= 
        ap_const_lv10_0 when (tmp_5_fu_554_p2(0) = '1') else 
        calo_5_hwPhi_V_read;
    calo_6_hwEta_V_read_1_fu_596_p3 <= 
        ap_const_lv10_0 when (tmp_6_fu_590_p2(0) = '1') else 
        calo_6_hwEta_V_read;
    calo_6_hwPhi_V_read_1_fu_604_p3 <= 
        ap_const_lv10_0 when (tmp_6_fu_590_p2(0) = '1') else 
        calo_6_hwPhi_V_read;
    calo_7_hwEta_V_read_1_fu_632_p3 <= 
        ap_const_lv10_0 when (tmp_7_fu_626_p2(0) = '1') else 
        calo_7_hwEta_V_read;
    calo_7_hwPhi_V_read_1_fu_640_p3 <= 
        ap_const_lv10_0 when (tmp_7_fu_626_p2(0) = '1') else 
        calo_7_hwPhi_V_read;
    calo_8_hwEta_V_read_1_fu_668_p3 <= 
        ap_const_lv10_0 when (tmp_8_fu_662_p2(0) = '1') else 
        calo_8_hwEta_V_read;
    calo_8_hwPhi_V_read_1_fu_676_p3 <= 
        ap_const_lv10_0 when (tmp_8_fu_662_p2(0) = '1') else 
        calo_8_hwPhi_V_read;
    calo_9_hwEta_V_read_1_fu_704_p3 <= 
        ap_const_lv10_0 when (tmp_9_fu_698_p2(0) = '1') else 
        calo_9_hwEta_V_read;
    calo_9_hwPhi_V_read_1_fu_712_p3 <= 
        ap_const_lv10_0 when (tmp_9_fu_698_p2(0) = '1') else 
        calo_9_hwPhi_V_read;
    pfout_0_hwId_V_writ_fu_402_p3 <= 
        ap_const_lv3_2 when (tmp_1_fu_396_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_10_hwId_V_wri_fu_762_p3 <= 
        ap_const_lv3_2 when (tmp_13_s_fu_756_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_11_hwId_V_wri_fu_798_p3 <= 
        ap_const_lv3_2 when (tmp_13_10_fu_792_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_12_hwId_V_wri_fu_834_p3 <= 
        ap_const_lv3_2 when (tmp_13_11_fu_828_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_13_hwId_V_wri_fu_870_p3 <= 
        ap_const_lv3_2 when (tmp_13_12_fu_864_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_14_hwId_V_wri_fu_906_p3 <= 
        ap_const_lv3_2 when (tmp_13_13_fu_900_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_1_hwId_V_writ_fu_438_p3 <= 
        ap_const_lv3_2 when (tmp_13_1_fu_432_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_2_hwId_V_writ_fu_474_p3 <= 
        ap_const_lv3_2 when (tmp_13_2_fu_468_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_3_hwId_V_writ_fu_510_p3 <= 
        ap_const_lv3_2 when (tmp_13_3_fu_504_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_4_hwId_V_writ_fu_546_p3 <= 
        ap_const_lv3_2 when (tmp_13_4_fu_540_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_5_hwId_V_writ_fu_582_p3 <= 
        ap_const_lv3_2 when (tmp_13_5_fu_576_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_6_hwId_V_writ_fu_618_p3 <= 
        ap_const_lv3_2 when (tmp_13_6_fu_612_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_7_hwId_V_writ_fu_654_p3 <= 
        ap_const_lv3_2 when (tmp_13_7_fu_648_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_8_hwId_V_writ_fu_690_p3 <= 
        ap_const_lv3_2 when (tmp_13_8_fu_684_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_9_hwId_V_writ_fu_726_p3 <= 
        ap_const_lv3_2 when (tmp_13_9_fu_720_p2(0) = '1') else 
        ap_const_lv3_0;
    tmp_10_fu_770_p2 <= "1" when (photonPt_11_V_read = ap_const_lv16_0) else "0";
    tmp_11_fu_806_p2 <= "1" when (photonPt_12_V_read = ap_const_lv16_0) else "0";
    tmp_12_fu_842_p2 <= "1" when (photonPt_13_V_read = ap_const_lv16_0) else "0";
    tmp_13_10_fu_792_p2 <= "0" when (photonPt_11_V_read = ap_const_lv16_0) else "1";
    tmp_13_11_fu_828_p2 <= "0" when (photonPt_12_V_read = ap_const_lv16_0) else "1";
    tmp_13_12_fu_864_p2 <= "0" when (photonPt_13_V_read = ap_const_lv16_0) else "1";
    tmp_13_13_fu_900_p2 <= "0" when (photonPt_14_V_read = ap_const_lv16_0) else "1";
    tmp_13_1_fu_432_p2 <= "0" when (photonPt_1_V_read = ap_const_lv16_0) else "1";
    tmp_13_2_fu_468_p2 <= "0" when (photonPt_2_V_read = ap_const_lv16_0) else "1";
    tmp_13_3_fu_504_p2 <= "0" when (photonPt_3_V_read = ap_const_lv16_0) else "1";
    tmp_13_4_fu_540_p2 <= "0" when (photonPt_4_V_read = ap_const_lv16_0) else "1";
    tmp_13_5_fu_576_p2 <= "0" when (photonPt_5_V_read = ap_const_lv16_0) else "1";
    tmp_13_6_fu_612_p2 <= "0" when (photonPt_6_V_read = ap_const_lv16_0) else "1";
    tmp_13_7_fu_648_p2 <= "0" when (photonPt_7_V_read = ap_const_lv16_0) else "1";
    tmp_13_8_fu_684_p2 <= "0" when (photonPt_8_V_read = ap_const_lv16_0) else "1";
    tmp_13_9_fu_720_p2 <= "0" when (photonPt_9_V_read = ap_const_lv16_0) else "1";
    tmp_13_fu_878_p2 <= "1" when (photonPt_14_V_read = ap_const_lv16_0) else "0";
    tmp_13_s_fu_756_p2 <= "0" when (photonPt_10_V_read = ap_const_lv16_0) else "1";
    tmp_1_16_fu_410_p2 <= "1" when (photonPt_1_V_read = ap_const_lv16_0) else "0";
    tmp_1_fu_396_p2 <= "0" when (photonPt_0_V_read = ap_const_lv16_0) else "1";
    tmp_2_fu_446_p2 <= "1" when (photonPt_2_V_read = ap_const_lv16_0) else "0";
    tmp_3_fu_482_p2 <= "1" when (photonPt_3_V_read = ap_const_lv16_0) else "0";
    tmp_4_fu_518_p2 <= "1" when (photonPt_4_V_read = ap_const_lv16_0) else "0";
    tmp_5_fu_554_p2 <= "1" when (photonPt_5_V_read = ap_const_lv16_0) else "0";
    tmp_6_fu_590_p2 <= "1" when (photonPt_6_V_read = ap_const_lv16_0) else "0";
    tmp_7_fu_626_p2 <= "1" when (photonPt_7_V_read = ap_const_lv16_0) else "0";
    tmp_8_fu_662_p2 <= "1" when (photonPt_8_V_read = ap_const_lv16_0) else "0";
    tmp_9_fu_698_p2 <= "1" when (photonPt_9_V_read = ap_const_lv16_0) else "0";
    tmp_s_17_fu_734_p2 <= "1" when (photonPt_10_V_read = ap_const_lv16_0) else "0";
    tmp_s_fu_374_p2 <= "1" when (photonPt_0_V_read = ap_const_lv16_0) else "0";
end behav;
